"""
DRF URL routing for the institutions module.

Design decisions (from design.md):
- SimpleRouter for Institution ViewSet
- Manual nested paths for sub-entities (avoids drf-nested-routers dependency)
- Lifecycle actions: activate/deactivate/archive as @action POST endpoints
- Prefix: /api/v1/ (applied at config/urls.py level)

API contract (from spec.md):
  /institutions/                          GET, POST
  /institutions/{id}/                     GET, PATCH, DELETE
  /institutions/{id}/sedes/               GET, POST
  /institutions/{id}/sedes/{id}/          GET, PATCH, DELETE
  /institutions/{id}/facultades/          GET, POST
  /institutions/{id}/facultades/{id}/     GET, PATCH, DELETE
  /institutions/{id}/centers/             GET, POST
  /institutions/{id}/centers/{id}/        GET, PATCH, DELETE
  /centers/{id}/groups/                   GET, POST
  /centers/{id}/groups/{id}/              GET, PATCH, DELETE
  /groups/{id}/lines/                     GET, POST
  /groups/{id}/lines/{id}/                GET, PATCH, DELETE
  /{entity}/{id}/activate/                POST
  /{entity}/{id}/deactivate/              POST
  /{entity}/{id}/archive/                 POST

Spec reference: openspec/changes/institutions/spec.md — API Contract
Design reference: openspec/changes/institutions/design.md — URL nesting
"""

from django.urls import include, path
from rest_framework.routers import SimpleRouter

from apps.institutions import views  # noqa: F401 — viewsets created in Phase 4

# ──────────────────────────────────────────────────────────
# Router: Institution
# ──────────────────────────────────────────────────────────

router = SimpleRouter()
router.register(r"institutions", views.InstitutionViewSet, basename="institution")

# ──────────────────────────────────────────────────────────
# Nested routes under /institutions/{institution_pk}/
# ──────────────────────────────────────────────────────────

institution_nested = [
    # Sedes
    path(
        "sedes/",
        views.SedeViewSet.as_view({"get": "list", "post": "create"}),
        name="institution-sede-list",
    ),
    path(
        "sedes/<uuid:pk>/",
        views.SedeViewSet.as_view(
            {"get": "retrieve", "patch": "partial_update", "delete": "destroy"}
        ),
        name="institution-sede-detail",
    ),
    # Facultades
    path(
        "facultades/",
        views.FacultadViewSet.as_view({"get": "list", "post": "create"}),
        name="institution-facultad-list",
    ),
    path(
        "facultades/<uuid:pk>/",
        views.FacultadViewSet.as_view(
            {"get": "retrieve", "patch": "partial_update", "delete": "destroy"}
        ),
        name="institution-facultad-detail",
    ),
    # Research Centers
    path(
        "centers/",
        views.ResearchCenterViewSet.as_view({"get": "list", "post": "create"}),
        name="institution-center-list",
    ),
    path(
        "centers/<uuid:pk>/",
        views.ResearchCenterViewSet.as_view(
            {"get": "retrieve", "patch": "partial_update", "delete": "destroy"}
        ),
        name="institution-center-detail",
    ),
]

# ──────────────────────────────────────────────────────────
# Nested routes under /centers/{center_pk}/
# ──────────────────────────────────────────────────────────

center_nested = [
    path(
        "groups/",
        views.ResearchGroupViewSet.as_view({"get": "list", "post": "create"}),
        name="center-group-list",
    ),
    path(
        "groups/<uuid:pk>/",
        views.ResearchGroupViewSet.as_view(
            {"get": "retrieve", "patch": "partial_update", "delete": "destroy"}
        ),
        name="center-group-detail",
    ),
]

# ──────────────────────────────────────────────────────────
# Nested routes under /groups/{group_pk}/
# ──────────────────────────────────────────────────────────

group_nested = [
    path(
        "lines/",
        views.ResearchLineViewSet.as_view({"get": "list", "post": "create"}),
        name="group-line-list",
    ),
    path(
        "lines/<uuid:pk>/",
        views.ResearchLineViewSet.as_view(
            {"get": "retrieve", "patch": "partial_update", "delete": "destroy"}
        ),
        name="group-line-detail",
    ),
]

# ──────────────────────────────────────────────────────────
# Lifecycle action routes (per entity)
# ──────────────────────────────────────────────────────────

# These custom actions expose activate/deactivate/archive as POST endpoints
# on each entity's detail view. The ViewSets implement @action decorators.

lifecycle_routes = [
    # Institution lifecycle routes are generated by SimpleRouter + @action decorators.
    # Only nested-entity lifecycle routes need explicit paths (router can't generate
    # nested URLs like /institutions/{inst_pk}/sedes/{pk}/activate/).
    # Sede lifecycle (under institution nesting)
    path(
        "institutions/<uuid:institution_pk>/sedes/<uuid:pk>/activate/",
        views.SedeViewSet.as_view({"post": "activate"}),
        name="sede-activate",
    ),
    path(
        "institutions/<uuid:institution_pk>/sedes/<uuid:pk>/deactivate/",
        views.SedeViewSet.as_view({"post": "deactivate"}),
        name="sede-deactivate",
    ),
    path(
        "institutions/<uuid:institution_pk>/sedes/<uuid:pk>/archive/",
        views.SedeViewSet.as_view({"post": "archive"}),
        name="sede-archive",
    ),
    # Facultad lifecycle
    path(
        "institutions/<uuid:institution_pk>/facultades/<uuid:pk>/activate/",
        views.FacultadViewSet.as_view({"post": "activate"}),
        name="facultad-activate",
    ),
    path(
        "institutions/<uuid:institution_pk>/facultades/<uuid:pk>/deactivate/",
        views.FacultadViewSet.as_view({"post": "deactivate"}),
        name="facultad-deactivate",
    ),
    path(
        "institutions/<uuid:institution_pk>/facultades/<uuid:pk>/archive/",
        views.FacultadViewSet.as_view({"post": "archive"}),
        name="facultad-archive",
    ),
    # Center lifecycle
    path(
        "institutions/<uuid:institution_pk>/centers/<uuid:pk>/activate/",
        views.ResearchCenterViewSet.as_view({"post": "activate"}),
        name="center-activate",
    ),
    path(
        "institutions/<uuid:institution_pk>/centers/<uuid:pk>/deactivate/",
        views.ResearchCenterViewSet.as_view({"post": "deactivate"}),
        name="center-deactivate",
    ),
    path(
        "institutions/<uuid:institution_pk>/centers/<uuid:pk>/archive/",
        views.ResearchCenterViewSet.as_view({"post": "archive"}),
        name="center-archive",
    ),
    # Group lifecycle
    path(
        "centers/<uuid:center_pk>/groups/<uuid:pk>/activate/",
        views.ResearchGroupViewSet.as_view({"post": "activate"}),
        name="group-activate",
    ),
    path(
        "centers/<uuid:center_pk>/groups/<uuid:pk>/deactivate/",
        views.ResearchGroupViewSet.as_view({"post": "deactivate"}),
        name="group-deactivate",
    ),
    path(
        "centers/<uuid:center_pk>/groups/<uuid:pk>/archive/",
        views.ResearchGroupViewSet.as_view({"post": "archive"}),
        name="group-archive",
    ),
    # Line lifecycle
    path(
        "groups/<uuid:group_pk>/lines/<uuid:pk>/activate/",
        views.ResearchLineViewSet.as_view({"post": "activate"}),
        name="line-activate",
    ),
    path(
        "groups/<uuid:group_pk>/lines/<uuid:pk>/deactivate/",
        views.ResearchLineViewSet.as_view({"post": "deactivate"}),
        name="line-deactivate",
    ),
    path(
        "groups/<uuid:group_pk>/lines/<uuid:pk>/archive/",
        views.ResearchLineViewSet.as_view({"post": "archive"}),
        name="line-archive",
    ),
]

# ──────────────────────────────────────────────────────────
# urlpatterns assembly
# ──────────────────────────────────────────────────────────

app_name = "institutions"

urlpatterns = (
    router.urls
    + [
        # Nested sub-entity routes under institutions
        path(
            "institutions/<uuid:institution_pk>/",
            include(institution_nested),
        ),
        # Nested routes under centers
        path(
            "centers/<uuid:center_pk>/",
            include(center_nested),
        ),
        # Nested routes under groups
        path(
            "groups/<uuid:group_pk>/",
            include(group_nested),
        ),
    ]
    + lifecycle_routes
)
