/**
 * ESLint 9 flat config wrapping the legacy next/typescript rules.
 * next/core-web-vitals and next/typescript are provided by eslint-config-next.
 */
import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const config = [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "coverage/**",
      "out/**",
      "public/mockServiceWorker.js",
      // Generated by `next dev`/`next build` (including the frontend dev
      // container); it uses triple-slash references that the Next lint rules
      // reject, and it is not source.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
];

export default config;
