# Generated by Django 5.1.15 on 2026-07-20 21:33

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0004_alter_facultad_status_alter_institution_status_and_more'),
        ('researchers', '0002_rls_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('objectives', models.TextField()),
                ('methodology', models.TextField()),
                ('expected_results', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', django_fsm.FSMField(default='borrador', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='institutions.researchcenter')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='institutions.researchgroup')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='institutions.institution')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='institutions.researchline')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to='researchers.researcher')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('proposal', 'Proposal'), ('annex', 'Annex'), ('contract', 'Contract'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('external_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'db_table': 'projects_projectdocument',
                'ordering': ['project', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('co_investigator', 'Co-Investigator'), ('student', 'Student'), ('seedbed', 'Seedbed'), ('collaborator', 'Collaborator')], max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='researchers.researcher')),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'db_table': 'projects_projectmember',
                'ordering': ['project', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_observations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Observation',
                'verbose_name_plural': 'Project Observations',
                'db_table': 'projects_projectobservation',
                'ordering': ['project', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='projects.project')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_state_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project State Log',
                'verbose_name_plural': 'Project State Logs',
                'db_table': 'projects_projectstatelog',
                'ordering': ['project', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['institution', 'status'], name='idx_project_inst_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['center', 'status'], name='idx_project_center_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['principal_investigator'], name='idx_project_pi'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_end_date__gte', models.F('start_date'))), name='check_estimated_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('actual_end_date__isnull', True), ('actual_end_date__gte', models.F('start_date')), _connector='OR'), name='check_actual_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'researcher'), name='unique_project_researcher'),
        ),
        migrations.AddIndex(
            model_name='projectstatelog',
            index=models.Index(fields=['project', '-created_at'], name='idx_statelog_project_time'),
        ),
        migrations.AddIndex(
            model_name='projectstatelog',
            index=models.Index(fields=['from_state', 'to_state'], name='idx_statelog_states'),
        ),
    ]
