# Generated by Django 5.1.15 on 2026-07-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rls_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cumulative_progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
