"""
RLS policy tests for products app.

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the products migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 3 product tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent table (products_researchproduct) uses direct institution_id
- Child tables (author/attachment) use a subquery via product_id
- PostgreSQL-only guard (no-op on SQLite)

The enforcement tests run on a real PostgreSQL connection assumed as the
least-privilege ``sigpi_app`` role (via the ``postgres_app_role`` fixture), so
row-level security genuinely applies. They seed one row per institution for
every protected table under a bypass context, then prove institution A's rows
are visible while institution B's stay denied, and that the superadmin bypass
reveals both.

Design reference: openspec/changes/products/design.md — RLS Policies
Pattern reference: apps/budgets/tests/test_rls.py
"""

import importlib
import inspect

from django.db import connection
from django.db.migrations.loader import MigrationLoader

from apps.institutions.tests.conftest import InstitutionFactory
from apps.products.models import ProductAttachment, ProductAuthor, ResearchProduct
from apps.products.tests.conftest import (
    ProductAttachmentFactory,
    ProductAuthorFactory,
    ProductFactory,
)
from apps.projects.tests.conftest import ProjectFactory

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "products_researchproduct",
    "products_productauthor",
    "products_productattachment",
]

# Tables that traverse a subquery (no direct institution_id column)
CHILD_TABLES = [
    "products_productauthor",  # via product_id
    "products_productattachment",  # via product_id
]

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the products 0002 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("products", "0002_rls_policies")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/products/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("products", "0001_initial") in deps, (
            f"Expected dependency on products.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. All 3 product tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_table_uses_direct_institution_id(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), (
            "products_researchproduct must use direct institution_id filter. Child tables use subquery."
        )

    def test_child_tables_use_subquery(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        # Author/attachment reach Institution through the parent product.
        assert "SELECT id FROM products_researchproduct" in sql, (
            "Child tables must subquery products_researchproduct by institution_id."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow the sibling-app pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────

TENANT_GUC = "sigpi.institution_id"
BYPASS_GUC = "sigpi.bypass_rls"


def _set_rls(conn, institution_id, bypass):
    """Write the RLS GUCs at connection scope, exactly like production does."""
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [TENANT_GUC, "" if institution_id is None else str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [BYPASS_GUC, "true" if bypass else "false"],
        )


def _seed_products(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    _set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="PGA", name="Institution PGA")
    inst_b = InstitutionFactory(code="PGB", name="Institution PGB")
    project_a = ProjectFactory(institution=inst_a, status="aprobado")
    project_b = ProjectFactory(institution=inst_b, status="aprobado")
    product_a = ProductFactory(project=project_a)
    product_b = ProductFactory(project=project_b)
    author_a = ProductAuthorFactory(product=product_a)
    author_b = ProductAuthorFactory(product=product_b)
    attachment_a = ProductAttachmentFactory(product=product_a)
    attachment_b = ProductAttachmentFactory(product=product_b)
    _set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "product_a": product_a,
        "product_b": product_b,
        "author_a": author_a,
        "author_b": author_b,
        "attachment_a": attachment_a,
        "attachment_b": attachment_b,
    }


def _assert_only_a_visible(model, pk_a, pk_b):
    """Non-vacuous assertion pair: A's row visible, B's row denied."""
    assert model.objects.filter(pk=pk_a).exists(), (
        f"{model.__name__}: institution A's seeded row is not visible under "
        f"institution A's tenant context."
    )
    assert model.objects.filter(pk=pk_b).count() == 0, (
        f"{model.__name__}: institution B's seeded row leaked into institution A's tenant context."
    )


def _assert_both_visible(model, pk_a, pk_b):
    """Bypass must reveal both institutions' rows, not merely zero rows."""
    both = model.objects.filter(pk__in=[pk_a, pk_b]).count()
    assert both == 2, (
        f"{model.__name__}: superadmin bypass exposed {both} of 2 seeded rows; "
        f"it must reveal more than a single tenant scope."
    )


class TestRLSEnforcement:
    """Cross-institution isolation for every protected products table."""

    def test_cross_institution_product_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_products(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ResearchProduct, rows["product_a"].pk, rows["product_b"].pk)

    def test_cross_institution_author_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_products(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ProductAuthor, rows["author_a"].pk, rows["author_b"].pk)

    def test_cross_institution_attachment_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_products(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ProductAttachment, rows["attachment_a"].pk, rows["attachment_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_products(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=True)
        _assert_both_visible(ResearchProduct, rows["product_a"].pk, rows["product_b"].pk)
        _assert_both_visible(ProductAuthor, rows["author_a"].pk, rows["author_b"].pk)
        _assert_both_visible(ProductAttachment, rows["attachment_a"].pk, rows["attachment_b"].pk)
