# Generated by Django 6.0.7 on 2026-08-25 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# ──────────────────────────────────────────────
# Seed data: 4 event-type templates (spec catalog)
# ──────────────────────────────────────────────

SEEDED_TEMPLATES = [
    {
        'code': 'PROJECT_SUBMITTED',
        'title_template': 'Proyecto enviado',
        'body_template': (
            'El proyecto «{{ project.title }}» fue enviado para revisión '
            'por el director del centro.'
        ),
    },
    {
        'code': 'PROGRESS_OBSERVED',
        'title_template': 'Avance observado',
        'body_template': (
            'El avance «{{ progress.title }}» fue observado y requiere '
            'correcciones antes de continuar.'
        ),
    },
    {
        'code': 'DOCUMENT_SIGNED',
        'title_template': 'Documento firmado',
        'body_template': (
            'El documento «{{ document.name }}» fue firmado digitalmente '
            'en la versión {{ version }}.'
        ),
    },
    {
        'code': 'BUDGET_OVERRUN_ATTEMPTED',
        'title_template': 'Intento de sobrepaso presupuestal',
        'body_template': (
            'Se intentó registrar una ejecución de ${{ amount }} sin '
            'autorización sobre la línea «{{ line.description }}».'
        ),
    },
]


def seed_templates(apps, schema_editor):
    """Seed the 4 event-type templates (idempotent)."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    for data in SEEDED_TEMPLATES:
        NotificationTemplate.objects.update_or_create(
            code=data['code'],
            defaults={
                'title_template': data['title_template'],
                'body_template': data['body_template'],
                'is_active': True,
            },
        )


def unseed_templates(apps, schema_editor):
    """Remove the seeded templates on reverse."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate.objects.filter(
        code__in=[data['code'] for data in SEEDED_TEMPLATES]
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0004_alter_facultad_status_alter_institution_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Event-type code this template renders (e.g. PROJECT_SUBMITTED)', max_length=50, unique=True)),
                ('title_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates suppress notification creation')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notifications_notificationtemplate',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(help_text='Denormalized institution for RLS tenant isolation', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='institutions.institution')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notifications_notificationlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'notifications_userpreference',
                'ordering': ['user'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_recipient_read_created'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event_type', 'entity_type', 'entity_id'), name='uniq_notif_event_per_recipient'),
        ),
        migrations.RunPython(
            code=seed_templates,
            reverse_code=unseed_templates,
        ),
    ]
