# Generated by Django 6.0.8 on 2026-09-28 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_rls"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="idx_notif_recip_read_created",
            old_name="idx_notif_recipient_read_created",
        ),
    ]
