"""
RLS policy tests for project_workflow app — STRICT TDD.

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 4 workflow tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent tables use direct institution_id
- Child tables use subquery via template_id / instance_id
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/project_workflow/spec.md — WR-006
Design reference: openspec/changes/project_workflow/design.md — RLS Policies
Pattern reference: apps/projects/tests/test_rls.py
"""

import importlib
import inspect
import json

import pytest
from django.test import Client
from django.urls import reverse

from apps.accounts.tests._helpers import get_role
from apps.institutions.tests.conftest import InstitutionFactory
from apps.project_workflow.models import (
    WorkflowAction,
    WorkflowInstance,
    WorkflowStep,
    WorkflowTemplate,
)
from apps.project_workflow.tests.conftest import (
    WorkflowActionFactory,
    WorkflowInstanceFactory,
    WorkflowStepFactory,
    WorkflowTemplateFactory,
)
from tests.rls_helpers import (
    assert_both_visible,
    assert_only_a_visible,
    get_all_sql,
    get_apply_function_source,
    load_migration,
    set_rls,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "project_workflow_workflowtemplate",
    "project_workflow_workflowinstance",
    "project_workflow_workflowstep",
    "project_workflow_workflowaction",
]

# Parent tables that use a direct institution_id column
PARENT_TABLES = [
    "project_workflow_workflowtemplate",
    "project_workflow_workflowinstance",
]

# Child tables that use a subquery (no direct institution_id)
CHILD_TABLES = [
    "project_workflow_workflowstep",
    "project_workflow_workflowaction",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        """Migration 0002_rls_policies must exist on disk."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/project_workflow/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        """Migration 0002 must depend on 0001_initial."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("project_workflow", "0001_initial") in deps, (
            f"Expected dependency on project_workflow.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have RLS policies in the migration SQL."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. "
                f"All 4 workflow tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table must have a tenant_isolation policy."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_tables_use_direct_institution_id(self, db):
        """Parent tables must filter by institution_id directly."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in PARENT_TABLES:
            assert (
                "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
                in sql
            ), f"Parent table '{table}' must use direct institution_id filter."

    def test_child_tables_use_subquery(self, db):
        """Child tables must filter via subquery through parent table."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in CHILD_TABLES:
            assert "IN (" in sql and "project_workflow_" in sql, (
                f"Child table '{table}' must use a subquery through parent."
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends"
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = load_migration("project_workflow", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        source = get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, "Forward function must guard against non-PostgreSQL."


# ──────────────────────────────────────────────
# Test: Application-level tenant scoping (SQLite-safe)
# ──────────────────────────────────────────────


@pytest.mark.django_db
class TestApplicationLevelTenantScoping:
    """Verify ViewSet querysets scope by institution even on SQLite."""

    def test_template_queryset_scoped_by_institution(self):
        from apps.accounts.models import InstitutionMembership, User
        from apps.institutions.models import Institution
        from apps.project_workflow.models import WorkflowTemplate

        inst_a = Institution.objects.create(name="A", code="A")
        inst_b = Institution.objects.create(name="B", code="B")

        WorkflowTemplate.objects.create(institution=inst_a, name="A-Template")
        WorkflowTemplate.objects.create(institution=inst_b, name="B-Template")

        user = User.objects.create_user(email="u@test.edu", password="p")
        role = get_role("Admin Institucional")
        InstitutionMembership.objects.create(
            user=user, institution=inst_a, role=role, is_active=True
        )

        client = Client()
        client.force_login(user)
        session = client.session
        session["institution_id"] = str(inst_a.id)
        session.save()

        response = client.get(reverse("project_workflow:workflowtemplate-list"))
        assert response.status_code == 200
        data = json.loads(response.content)
        names = [t["name"] for t in data["results"]]
        assert "A-Template" in names
        assert "B-Template" not in names

    def test_instance_queryset_scoped_by_institution(self):
        from apps.accounts.models import InstitutionMembership, User
        from apps.institutions.models import Institution
        from apps.project_workflow.models import WorkflowInstance, WorkflowTemplate

        inst_a = Institution.objects.create(name="A", code="A")
        inst_b = Institution.objects.create(name="B", code="B")
        template_a = WorkflowTemplate.objects.create(institution=inst_a, name="TA")
        template_b = WorkflowTemplate.objects.create(institution=inst_b, name="TB")

        import uuid

        WorkflowInstance.objects.create(
            project_id=uuid.uuid4(), institution=inst_a, template=template_a
        )
        WorkflowInstance.objects.create(
            project_id=uuid.uuid4(), institution=inst_b, template=template_b
        )

        user = User.objects.create_user(email="u2@test.edu", password="p")
        role = get_role("Director de Centro")
        InstitutionMembership.objects.create(
            user=user, institution=inst_a, role=role, is_active=True
        )

        client = Client()
        client.force_login(user)
        session = client.session
        session["institution_id"] = str(inst_a.id)
        session.save()

        response = client.get(reverse("project_workflow:workflowinstance-list"))
        assert response.status_code == 200
        data = json.loads(response.content)
        # Should only see instances from institution A
        assert len(data["results"]) == 1

    def test_superadmin_sees_all_templates(self):
        from apps.accounts.models import User
        from apps.institutions.models import Institution
        from apps.project_workflow.models import WorkflowTemplate

        inst_a = Institution.objects.create(name="A", code="A")
        inst_b = Institution.objects.create(name="B", code="B")
        WorkflowTemplate.objects.create(institution=inst_a, name="TA")
        WorkflowTemplate.objects.create(institution=inst_b, name="TB")

        superuser = User.objects.create_superuser(email="sa@test.edu", password="p")

        client = Client()
        client.force_login(superuser)
        session = client.session
        session["institution_id"] = str(inst_a.id)
        session.save()

        response = client.get(reverse("project_workflow:workflowtemplate-list"))
        assert response.status_code == 200
        data = json.loads(response.content)
        assert len(data["results"]) == 2


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────


def _seed_workflow(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="BGA", name="Institution BGA")
    inst_b = InstitutionFactory(code="BGB", name="Institution BGB")
    template_a = WorkflowTemplateFactory(institution=inst_a)
    template_b = WorkflowTemplateFactory(institution=inst_b)
    step_a = WorkflowStepFactory(template=template_a)
    step_b = WorkflowStepFactory(template=template_b)
    instance_a = WorkflowInstanceFactory(template=template_a)
    instance_b = WorkflowInstanceFactory(template=template_b)
    action_a = WorkflowActionFactory(instance=instance_a)
    action_b = WorkflowActionFactory(instance=instance_b)
    set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "template_a": template_a,
        "template_b": template_b,
        "step_a": step_a,
        "step_b": step_b,
        "instance_a": instance_a,
        "instance_b": instance_b,
        "action_a": action_a,
        "action_b": action_b,
    }


class TestRLSEnforcement:
    """Cross-institution isolation for every protected workflow table."""

    def test_cross_institution_template_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_workflow(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(WorkflowTemplate, rows["template_a"].pk, rows["template_b"].pk)

    def test_cross_institution_instance_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_workflow(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(WorkflowInstance, rows["instance_a"].pk, rows["instance_b"].pk)

    def test_cross_institution_step_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_workflow(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(WorkflowStep, rows["step_a"].pk, rows["step_b"].pk)

    def test_cross_institution_action_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_workflow(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(WorkflowAction, rows["action_a"].pk, rows["action_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_workflow(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=True)
        assert_both_visible(WorkflowTemplate, rows["template_a"].pk, rows["template_b"].pk)
        assert_both_visible(WorkflowInstance, rows["instance_a"].pk, rows["instance_b"].pk)
        assert_both_visible(WorkflowStep, rows["step_a"].pk, rows["step_b"].pk)
        assert_both_visible(WorkflowAction, rows["action_a"].pk, rows["action_b"].pk)
