"""
RLS policy tests for notifications app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls.py:
- Migration class exists in the notifications migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 4 notifications tables
- tenant_isolation + superadmin_bypass policies present for each table
- Notification (parent) uses direct institution_id
- NotificationLog uses subquery via notification_id → notifications_notification
- UserPreference uses subquery via user_id → accounts_institutionmembership
- NotificationTemplate uses an explicit global policy (catalog data)
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/notifications/spec.md — Tenancy
Design reference: openspec/changes/notifications/design.md — RLS Policies
Pattern reference: calls/migrations/0002_rls_policies.py

RED PHASE: Tests fail because 0002_rls.py does not exist.
"""

import importlib
import inspect

import pytest
from django.db import connection
from django.db.migrations.loader import MigrationLoader

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "notifications_notification",
    "notifications_notificationtemplate",
    "notifications_notificationlog",
    "notifications_userpreference",
]

# Tables that use a subquery (no direct institution_id column)
SUBQUERY_TABLES = [
    "notifications_notificationlog",
    "notifications_userpreference",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the notifications 0002 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("notifications", "0002_rls")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        """Migration 0002_rls must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0002_rls not found. "
            "Expected at: apps/notifications/migrations/0002_rls.py"
        )

    def test_depends_on_0001(self, db):
        """Migration 0002 must depend on 0001_initial."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("notifications", "0001_initial") in deps, (
            f"Expected dependency on notifications.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        """Collect all SQL from the migration module."""
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have RLS policies in the migration SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. "
                f"All 4 notifications tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table must have a tenant_isolation policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_notification_uses_direct_institution_id(self, db):
        """Notification table must filter by institution_id directly."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "institution_id = current_setting" in sql, (
            "notifications_notification must use direct institution_id filter."
        )

    def test_notificationlog_uses_subquery(self, db):
        """NotificationLog must filter via subquery through notification_id."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "notification_id IN" in sql, (
            "notifications_notificationlog must use a subquery through "
            "notification_id → notifications_notification.institution_id."
        )
        assert "FROM notifications_notification" in sql, (
            "NotificationLog subquery must reference notifications_notification."
        )

    def test_userpreference_uses_membership_subquery(self, db):
        """UserPreference must scope through active institution memberships."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "user_id IN" in sql, (
            "notifications_userpreference must use a subquery through "
            "user_id → accounts_institutionmembership."
        )
        assert "FROM accounts_institutionmembership" in sql, (
            "UserPreference subquery must reference accounts_institutionmembership."
        )
        assert "is_active" in sql, (
            "UserPreference subquery must filter on active memberships."
        )

    def test_template_uses_global_policy(self, db):
        """NotificationTemplate is catalog data — explicit global policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        pattern = f"CREATE POLICY tenant_isolation ON {EXPECTED_RLS_TABLES[1]}"
        assert pattern in sql, "tenant_isolation policy missing for template table"
        assert "USING (true)" in sql, (
            "NotificationTemplate must have an explicit global policy "
            "(USING (true)) because templates are catalog data."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow calls/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite)
# ──────────────────────────────────────────────


@pytest.mark.skip(reason="Requires PostgreSQL with RLS support")
class TestRLSEnforcement:
    """Cross-institution isolation tests — PostgreSQL only.

    These tests verify that RLS policies actually enforce tenant
    isolation at the database level. Marked @pytest.mark.skip
    because they require a PostgreSQL backend.
    """

    def test_cross_institution_notification_invisible(self, db):
        """A notification from another institution is not visible."""
        pass

    def test_cross_institution_log_invisible(self, db):
        """A log of a notification from another institution is not visible."""
        pass

    def test_cross_institution_preference_invisible(self, db):
        """A preference of a user without membership in the institution is hidden."""
        pass

    def test_template_catalog_visible_to_all(self, db):
        """Templates (catalog data) remain visible under tenant isolation."""
        pass

    def test_superadmin_bypass_sees_all(self, db):
        """Superadmin bypass flag makes all rows visible."""
        pass
