"""
RLS policy tests for notifications app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls.py:
- Migration class exists in the notifications migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 4 notifications tables
- tenant_isolation + superadmin_bypass policies present for each table
- Notification (parent) uses direct institution_id
- NotificationLog uses subquery via notification_id → notifications_notification
- UserPreference uses subquery via user_id → accounts_institutionmembership
- NotificationTemplate uses an explicit global policy (catalog data)
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/notifications/spec.md — Tenancy
Design reference: openspec/changes/notifications/design.md — RLS Policies
Pattern reference: calls/migrations/0002_rls_policies.py

RED PHASE: Tests fail because 0002_rls.py does not exist.
"""

import importlib
import inspect
import uuid

import pytest
from django.db import connection
from django.db.migrations.loader import MigrationLoader

from apps.notifications.models import (
    Notification,
    NotificationLog,
    NotificationTemplate,
    UserPreference,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "notifications_notification",
    "notifications_notificationtemplate",
    "notifications_notificationlog",
    "notifications_userpreference",
]

# Tables that use a subquery (no direct institution_id column)
SUBQUERY_TABLES = [
    "notifications_notificationlog",
    "notifications_userpreference",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the notifications 0002 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("notifications", "0002_rls")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        """Migration 0002_rls must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0002_rls not found. "
            "Expected at: apps/notifications/migrations/0002_rls.py"
        )

    def test_depends_on_0001(self, db):
        """Migration 0002 must depend on 0001_initial."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("notifications", "0001_initial") in deps, (
            f"Expected dependency on notifications.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        """Collect all SQL from the migration module."""
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have RLS policies in the migration SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. "
                f"All 4 notifications tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table must have a tenant_isolation policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_notification_uses_direct_institution_id(self, db):
        """Notification table must filter by institution_id directly."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "institution_id = current_setting" in sql, (
            "notifications_notification must use direct institution_id filter."
        )

    def test_notificationlog_uses_subquery(self, db):
        """NotificationLog must filter via subquery through notification_id."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "notification_id IN" in sql, (
            "notifications_notificationlog must use a subquery through "
            "notification_id → notifications_notification.institution_id."
        )
        assert "FROM notifications_notification" in sql, (
            "NotificationLog subquery must reference notifications_notification."
        )

    def test_userpreference_uses_membership_subquery(self, db):
        """UserPreference must scope through active institution memberships."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "user_id IN" in sql, (
            "notifications_userpreference must use a subquery through "
            "user_id → accounts_institutionmembership."
        )
        assert "FROM accounts_institutionmembership" in sql, (
            "UserPreference subquery must reference accounts_institutionmembership."
        )
        assert "is_active" in sql, (
            "UserPreference subquery must filter on active memberships."
        )

    def test_template_uses_global_policy(self, db):
        """NotificationTemplate is catalog data — explicit global policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        pattern = f"CREATE POLICY tenant_isolation ON {EXPECTED_RLS_TABLES[1]}"
        assert pattern in sql, "tenant_isolation policy missing for template table"
        assert "USING (true)" in sql, (
            "NotificationTemplate must have an explicit global policy "
            "(USING (true)) because templates are catalog data."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow calls/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite)
# ──────────────────────────────────────────────


def _make_institution(code="TU"):
    from apps.institutions.models import Institution

    return Institution.objects.create(name=f"Test University {code}", code=code)


def _make_user(email="user@test.edu"):
    from apps.accounts.models import User

    return User.objects.create_user(email=email)


def _make_role(name, level):
    from apps.accounts.models import Role

    role, _ = Role.objects.get_or_create(name=name, defaults={"level": level})
    return role


def _make_membership(user, institution, role):
    from apps.accounts.models import InstitutionMembership

    return InstitutionMembership.objects.create(
        user=user,
        institution=institution,
        role=role,
    )


def _make_notification(recipient, institution):
    """A Notification row as created by the receivers (seeded template)."""
    template = NotificationTemplate.objects.get(code="PROJECT_SUBMITTED")
    return Notification.objects.create(
        institution=institution,
        recipient=recipient,
        event_type="PROJECT_SUBMITTED",
        template=template,
        title="Test notification",
        body="Test body",
        entity_type="project",
        entity_id=uuid.uuid4(),
    )


def _set_rls_context(connection, institution_id, bypass=False):
    """Scope the RLS session variables to the current test transaction.

    set_config(..., true) is transaction-local: it lasts for the rest of
    the pytest-django test transaction and is rolled back with it.
    Both variables are always set — the tenant_isolation policy reads
    sigpi.institution_id without missing_ok and would raise if unset.
    """
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT set_config('sigpi.institution_id', %s, true)",
            [str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config('sigpi.bypass_rls', %s, true)",
            ["true" if bypass else "false"],
        )


@pytest.fixture
def postgres_rls(db):
    """PostgreSQL-only RLS enforcement context — skip on SQLite."""
    if connection.vendor != "postgresql":
        pytest.skip("RLS enforcement requires PostgreSQL")
    return connection


class TestRLSEnforcement:
    """Cross-institution isolation tests — PostgreSQL only (skip on SQLite).

    RLS is institution-scoped, not recipient-scoped: within one
    institution every Notification row is visible to every member
    (tenant_isolation keyed by the denormalized institution_id).
    Same-institution recipient isolation is enforced at the queryset
    layer (recipient == request.user → cross-user 404, see test_api.py);
    RLS guarantees cross-institution isolation plus the superadmin bypass.
    """

    def test_cross_institution_notification_invisible(self, db, postgres_rls):
        """A Notification from another institution is not visible."""
        inst_a = _make_institution("A1")
        inst_b = _make_institution("B1")
        user_a = _make_user("a@test.edu")
        user_b = _make_user("b@test.edu")

        # Rows are created under bypass so INSERT WITH CHECK cannot block.
        _set_rls_context(postgres_rls, inst_a.pk, bypass=True)
        notif_a = _make_notification(user_a, inst_a)
        notif_b = _make_notification(user_b, inst_b)

        _set_rls_context(postgres_rls, inst_a.pk, bypass=False)
        visible = list(Notification.objects.all())

        assert notif_a in visible
        assert notif_b not in visible

    def test_user_a_cannot_read_user_b_notifications(self, db, postgres_rls):
        """User A's tenant session cannot read user B's notification (RN cross-tenant)."""
        inst_a = _make_institution("A1")
        inst_b = _make_institution("B1")
        user_a = _make_user("a@test.edu")
        user_b = _make_user("b@test.edu")

        _set_rls_context(postgres_rls, inst_a.pk, bypass=True)
        notif_a = _make_notification(user_a, inst_a)
        _set_rls_context(postgres_rls, inst_b.pk, bypass=True)
        notif_b = _make_notification(user_b, inst_b)

        # User A acts inside institution A — user B's notification lives in B.
        _set_rls_context(postgres_rls, inst_a.pk, bypass=False)
        assert Notification.objects.filter(pk=notif_a.pk).exists()
        assert not Notification.objects.filter(pk=notif_b.pk).exists()

    def test_admin_can_read_any_notification(self, db, postgres_rls):
        """An admin of an institution can read ANY row of that institution.

        RLS filters by institution, not recipient: a notification for
        another recipient in the same institution stays visible to the
        admin's tenant session. Cross-recipient reads within a tenant are
        additionally guarded by the API queryset (recipient=request.user).
        """
        inst = _make_institution("A1")
        admin = _make_user("admin@test.edu")
        other = _make_user("other@test.edu")
        admin_role = _make_role("Admin Institucional", 2)
        _make_membership(admin, inst, admin_role)

        _set_rls_context(postgres_rls, inst.pk, bypass=True)
        # The notification belongs to ANOTHER recipient in the same institution.
        notif_other = _make_notification(other, inst)

        _set_rls_context(postgres_rls, inst.pk, bypass=False)
        assert Notification.objects.filter(pk=notif_other.pk).exists()

    def test_cross_institution_log_invisible(self, db, postgres_rls):
        """A NotificationLog of another institution's notification is hidden."""
        inst_a = _make_institution("A1")
        inst_b = _make_institution("B1")
        user_b = _make_user("b@test.edu")

        _set_rls_context(postgres_rls, inst_b.pk, bypass=True)
        notif_b = _make_notification(user_b, inst_b)
        log = NotificationLog.objects.create(
            notification=notif_b,
            channel="email",
            recipient_email=user_b.email,
            status="sent",
        )

        _set_rls_context(postgres_rls, inst_a.pk, bypass=False)
        assert not NotificationLog.objects.filter(pk=log.pk).exists()

    def test_cross_institution_preference_invisible(self, db, postgres_rls):
        """A preference of a user without membership in the institution is hidden."""
        inst_a = _make_institution("A1")
        inst_b = _make_institution("B1")
        user_b = _make_user("b@test.edu")
        role = _make_role("Investigador", 4)

        _set_rls_context(postgres_rls, inst_b.pk, bypass=True)
        _make_membership(user_b, inst_b, role)
        pref = UserPreference.objects.create(
            user=user_b, channel="email", enabled=False
        )

        # user_b has no active membership in institution A → preference hidden.
        _set_rls_context(postgres_rls, inst_a.pk, bypass=False)
        assert not UserPreference.objects.filter(pk=pref.pk).exists()

        # Back in institution B (active membership) → visible again.
        _set_rls_context(postgres_rls, inst_b.pk, bypass=False)
        assert UserPreference.objects.filter(pk=pref.pk).exists()

    def test_template_catalog_visible_to_all(self, db, postgres_rls):
        """Templates (catalog data) remain visible under tenant isolation."""
        inst_a = _make_institution("A1")

        _set_rls_context(postgres_rls, inst_a.pk, bypass=False)
        assert NotificationTemplate.objects.count() >= 4

    def test_superadmin_bypass_sees_all(self, db, postgres_rls):
        """Superadmin bypass flag makes all rows visible."""
        inst_a = _make_institution("A1")
        inst_b = _make_institution("B1")
        user_a = _make_user("a@test.edu")
        user_b = _make_user("b@test.edu")

        _set_rls_context(postgres_rls, inst_b.pk, bypass=True)
        notif_b = _make_notification(user_b, inst_b)
        _set_rls_context(postgres_rls, inst_a.pk, bypass=True)
        notif_a = _make_notification(user_a, inst_a)

        _set_rls_context(postgres_rls, inst_a.pk, bypass=False)
        assert not Notification.objects.filter(pk=notif_b.pk).exists()
        assert Notification.objects.filter(pk=notif_a.pk).exists()

        _set_rls_context(postgres_rls, inst_a.pk, bypass=True)
        assert Notification.objects.filter(pk=notif_b.pk).exists()
        assert Notification.objects.filter(pk=notif_a.pk).exists()
