"""
RLS policy tests for documents app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the documents migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 4 documents tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent tables (documents_document, documents_minutes) use direct
  institution_id (denormalized column)
- Child tables use FK subqueries:
    documents_documentversion    → document_id → documents_document
    documents_digitalsignature   → document_version_id → documents_documentversion
      → documents_document
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/attachments/specs/documents/spec.md — RLS
Design reference: openspec/changes/attachments/design.md — RLS Policies
Pattern reference: apps/calls/tests/test_rls.py

RED PHASE: Tests fail because 0002_rls_policies.py does not exist.
"""

import importlib
import inspect

from django.db import connection
from django.db.migrations.loader import MigrationLoader

from apps.documents.models import (
    DigitalSignature,
    Document,
    DocumentVersion,
    Minutes,
)
from apps.documents.tests.conftest import (
    DigitalSignatureFactory,
    DocumentFactory,
    DocumentVersionFactory,
    MinutesFactory,
)
from apps.institutions.tests.conftest import InstitutionFactory

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "documents_document",
    "documents_minutes",
    "documents_documentversion",
    "documents_digitalsignature",
]

# Parent tables with a direct (denormalized) institution_id column
PARENT_TABLES = [
    "documents_document",
    "documents_minutes",
]

# Child tables that reach institution via FK subqueries
CHILD_TABLES = [
    "documents_documentversion",
    "documents_digitalsignature",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the documents 0002 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("documents", "0002_rls_policies")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        """Migration 0002_rls_policies must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/documents/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        """Migration 0002 must depend on 0001_initial."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("documents", "0001_initial") in deps, (
            f"Expected dependency on documents.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython.RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        """Collect all SQL from the migration module."""
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have RLS policies in the migration SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. "
                "All 4 documents tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table must have a tenant_isolation policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_tables_use_direct_institution_id(self, db):
        """Document and Minutes filter by institution_id directly (column exists)."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in PARENT_TABLES:
            assert f"CREATE POLICY tenant_isolation ON {table}" in sql
            assert (
                "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
                in sql
            ), f"{table} must use direct institution_id filter. Child tables use subquery."

    def test_version_child_table_uses_document_subquery(self, db):
        """DocumentVersion must filter via subquery through document_id."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "document_id IN" in sql, (
            "documents_documentversion must use a subquery through "
            "document_id → documents_document.institution_id."
        )
        assert "SELECT id FROM documents_document" in sql, (
            "documents_documentversion subquery must select from documents_document."
        )

    def test_signature_child_table_uses_nested_subquery(self, db):
        """DigitalSignature must filter via document_version_id → document."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "document_version_id IN" in sql, (
            "documents_digitalsignature must use a subquery through document_version_id."
        )
        assert "SELECT id FROM documents_documentversion" in sql, (
            "documents_digitalsignature subquery must select from documents_documentversion."
        )
        assert "SELECT id FROM documents_document" in sql, (
            "documents_digitalsignature subquery must reach documents_document.institution_id."
        )

    def test_disable_rls_sql_covers_all_tables(self, db):
        """Reverse SQL must drop policies and disable RLS on every table."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        disable_sql = getattr(mod, "DISABLE_RLS_SQL", "")
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY" in disable_sql, (
                f"DISABLE ROW LEVEL SECURITY missing for '{table}' in reverse SQL."
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow calls/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────

TENANT_GUC = "sigpi.institution_id"
BYPASS_GUC = "sigpi.bypass_rls"


def _set_rls(conn, institution_id, bypass):
    """Write the RLS GUCs at connection scope, exactly like production does."""
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [TENANT_GUC, "" if institution_id is None else str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [BYPASS_GUC, "true" if bypass else "false"],
        )


def _seed_documents(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    _set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="DCA", name="Institution DCA")
    inst_b = InstitutionFactory(code="DCB", name="Institution DCB")
    document_a = DocumentFactory(institution=inst_a)
    document_b = DocumentFactory(institution=inst_b)
    version_a = DocumentVersionFactory(document=document_a)
    version_b = DocumentVersionFactory(document=document_b)
    signature_a = DigitalSignatureFactory(document_version=version_a)
    signature_b = DigitalSignatureFactory(document_version=version_b)
    # Minutes must be backed by an UNSIGNED document: signing a document makes
    # it immutable, and Minutes.clean() rejects a signed backing document.
    minutes_document_a = DocumentFactory(institution=inst_a)
    minutes_document_b = DocumentFactory(institution=inst_b)
    minutes_a = MinutesFactory(institution=inst_a, document=minutes_document_a)
    minutes_b = MinutesFactory(institution=inst_b, document=minutes_document_b)
    _set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "document_a": document_a,
        "document_b": document_b,
        "version_a": version_a,
        "version_b": version_b,
        "signature_a": signature_a,
        "signature_b": signature_b,
        "minutes_a": minutes_a,
        "minutes_b": minutes_b,
    }


def _assert_only_a_visible(model, pk_a, pk_b):
    """Non-vacuous assertion pair: A's row visible, B's row denied."""
    assert model.objects.filter(pk=pk_a).exists(), (
        f"{model.__name__}: institution A's seeded row is not visible under "
        f"institution A's tenant context."
    )
    assert model.objects.filter(pk=pk_b).count() == 0, (
        f"{model.__name__}: institution B's seeded row leaked into institution A's tenant context."
    )


def _assert_both_visible(model, pk_a, pk_b):
    """Bypass must reveal both institutions' rows, not merely zero rows."""
    both = model.objects.filter(pk__in=[pk_a, pk_b]).count()
    assert both == 2, (
        f"{model.__name__}: superadmin bypass exposed {both} of 2 seeded rows; "
        f"it must reveal more than a single tenant scope."
    )


class TestRLSEnforcement:
    """Cross-institution isolation for every protected documents table."""

    def test_cross_institution_document_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(Document, rows["document_a"].pk, rows["document_b"].pk)

    def test_cross_institution_minutes_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(Minutes, rows["minutes_a"].pk, rows["minutes_b"].pk)

    def test_cross_institution_version_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(DocumentVersion, rows["version_a"].pk, rows["version_b"].pk)

    def test_cross_institution_signature_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(DigitalSignature, rows["signature_a"].pk, rows["signature_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=True)
        _assert_both_visible(Document, rows["document_a"].pk, rows["document_b"].pk)
        _assert_both_visible(Minutes, rows["minutes_a"].pk, rows["minutes_b"].pk)
        _assert_both_visible(DocumentVersion, rows["version_a"].pk, rows["version_b"].pk)
        _assert_both_visible(DigitalSignature, rows["signature_a"].pk, rows["signature_b"].pk)
