"""
RLS policy tests for documents app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the documents migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 4 documents tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent tables (documents_document, documents_minutes) use direct
  institution_id (denormalized column)
- Child tables use FK subqueries:
    documents_documentversion    → document_id → documents_document
    documents_digitalsignature   → document_version_id → documents_documentversion
      → documents_document
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/attachments/specs/documents/spec.md — RLS
Design reference: openspec/changes/attachments/design.md — RLS Policies
Pattern reference: apps/calls/tests/test_rls.py

RED PHASE: Tests fail because 0002_rls_policies.py does not exist.
"""

import importlib
import inspect

from apps.documents.models import (
    DigitalSignature,
    Document,
    DocumentVersion,
    Minutes,
)
from apps.documents.tests.conftest import (
    DigitalSignatureFactory,
    DocumentFactory,
    DocumentVersionFactory,
    MinutesFactory,
)
from apps.institutions.tests.conftest import InstitutionFactory
from tests.rls_helpers import (
    assert_both_visible,
    assert_only_a_visible,
    get_all_sql,
    get_apply_function_source,
    load_migration,
    policy_using,
    set_rls,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "documents_document",
    "documents_minutes",
    "documents_documentversion",
    "documents_digitalsignature",
]

# Parent tables with a direct (denormalized) institution_id column
PARENT_TABLES = [
    "documents_document",
    "documents_minutes",
]

# Child tables that reach institution via FK subqueries
CHILD_TABLES = [
    "documents_documentversion",
    "documents_digitalsignature",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        """Migration 0002_rls_policies must exist on disk."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/documents/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        """Migration 0002 must depend on 0001_initial."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("documents", "0001_initial") in deps, (
            f"Expected dependency on documents.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython.RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have a tenant_isolation USING clause."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert policy_using(sql, table) is not None, (
                f"Table '{table}' missing a CREATE POLICY tenant_isolation with a "
                "USING clause. All 4 documents tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table's own tenant_isolation predicate must scope by the tenant GUC."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            predicate = policy_using(sql, table)
            assert predicate is not None, (
                f"'{table}': no CREATE POLICY tenant_isolation with a USING clause"
            )
            assert "sigpi.institution_id" in predicate, (
                f"'{table}': tenant_isolation predicate does not scope by the tenant GUC: "
                f"{predicate!r}"
            )

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_tables_use_direct_institution_id(self, db):
        """Document and Minutes filter by institution_id directly (column exists)."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in PARENT_TABLES:
            predicate = policy_using(sql, table)
            assert predicate is not None, f"{table}: no tenant_isolation USING clause"
            assert "institution_id" in predicate, (
                f"{table} must use direct institution_id filter. Child tables use subquery."
            )

    def test_version_child_table_uses_document_subquery(self, db):
        """DocumentVersion must filter via subquery through document_id."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        predicate = policy_using(sql, "documents_documentversion")
        assert predicate is not None, "documents_documentversion: no tenant_isolation USING clause"
        assert "document_id" in predicate and "documents_document" in predicate, (
            "documents_documentversion must use a subquery through "
            f"document_id → documents_document.institution_id: {predicate!r}"
        )

    def test_signature_child_table_uses_nested_subquery(self, db):
        """DigitalSignature must filter via document_version_id → document."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        predicate = policy_using(sql, "documents_digitalsignature")
        assert predicate is not None, "documents_digitalsignature: no tenant_isolation USING clause"
        assert "document_version_id" in predicate and "documents_documentversion" in predicate, (
            "documents_digitalsignature must use a subquery through document_version_id "
            f"into documents_documentversion: {predicate!r}"
        )
        assert "FROM documents_document WHERE" in predicate, (
            "documents_digitalsignature subquery must reach "
            f"documents_document.institution_id: {predicate!r}"
        )

    def test_disable_rls_sql_covers_all_tables(self, db):
        """Reverse SQL must drop policies and disable RLS on every table."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        disable_sql = getattr(mod, "DISABLE_RLS_SQL", "")
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY" in disable_sql, (
                f"DISABLE ROW LEVEL SECURITY missing for '{table}' in reverse SQL."
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow calls/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = load_migration("documents", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        source = get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────


def _seed_documents(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="DCA", name="Institution DCA")
    inst_b = InstitutionFactory(code="DCB", name="Institution DCB")
    document_a = DocumentFactory(institution=inst_a)
    document_b = DocumentFactory(institution=inst_b)
    version_a = DocumentVersionFactory(document=document_a)
    version_b = DocumentVersionFactory(document=document_b)
    signature_a = DigitalSignatureFactory(document_version=version_a)
    signature_b = DigitalSignatureFactory(document_version=version_b)
    # Minutes must be backed by an UNSIGNED document: signing a document makes
    # it immutable, and Minutes.clean() rejects a signed backing document.
    minutes_document_a = DocumentFactory(institution=inst_a)
    minutes_document_b = DocumentFactory(institution=inst_b)
    minutes_a = MinutesFactory(institution=inst_a, document=minutes_document_a)
    minutes_b = MinutesFactory(institution=inst_b, document=minutes_document_b)
    set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "document_a": document_a,
        "document_b": document_b,
        "version_a": version_a,
        "version_b": version_b,
        "signature_a": signature_a,
        "signature_b": signature_b,
        "minutes_a": minutes_a,
        "minutes_b": minutes_b,
    }


class TestRLSEnforcement:
    """Cross-institution isolation for every protected documents table."""

    def test_cross_institution_document_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(Document, rows["document_a"].pk, rows["document_b"].pk)

    def test_cross_institution_minutes_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(Minutes, rows["minutes_a"].pk, rows["minutes_b"].pk)

    def test_cross_institution_version_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(DocumentVersion, rows["version_a"].pk, rows["version_b"].pk)

    def test_cross_institution_signature_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(DigitalSignature, rows["signature_a"].pk, rows["signature_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_documents(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=True)
        assert_both_visible(Document, rows["document_a"].pk, rows["document_b"].pk)
        assert_both_visible(Minutes, rows["minutes_a"].pk, rows["minutes_b"].pk)
        assert_both_visible(DocumentVersion, rows["version_a"].pk, rows["version_b"].pk)
        assert_both_visible(DigitalSignature, rows["signature_a"].pk, rows["signature_b"].pk)
