# Generated by Django 5.1.15 on 2026-07-21 04:02

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0004_alter_facultad_status_alter_institution_status_and_more'),
        ('projects', '0003_project_cumulative_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('description', models.TextField()),
                ('cumulative_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activities', models.TextField()),
                ('difficulties', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('status', django_fsm.FSMField(default='borrador', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_progress_reports', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='institutions.institution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'Progress Report',
                'verbose_name_plural': 'Progress Reports',
                'db_table': 'progress_progressreport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('evidence', 'Evidence'), ('annex', 'Annex'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('progress_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='progress.progressreport')),
            ],
            options={
                'verbose_name': 'Progress Document',
                'verbose_name_plural': 'Progress Documents',
                'db_table': 'progress_progressdocument',
                'ordering': ['progress_report', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('review_type', models.CharField(choices=[('observation', 'Observation'), ('rejection', 'Rejection')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='progress.progressreport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Review',
                'verbose_name_plural': 'Progress Reviews',
                'db_table': 'progress_progressreview',
                'ordering': ['progress_report', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressStateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='progress.progressreport')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_state_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress State Log',
                'verbose_name_plural': 'Progress State Logs',
                'db_table': 'progress_progressstatelog',
                'ordering': ['progress_report', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['institution', 'status'], name='idx_progress_inst_status'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['project', 'status'], name='idx_progress_project_status'),
        ),
        migrations.AddIndex(
            model_name='progressreport',
            index=models.Index(fields=['created_by'], name='idx_progress_created_by'),
        ),
        migrations.AddConstraint(
            model_name='progressreport',
            constraint=models.CheckConstraint(condition=models.Q(('cumulative_percentage__gte', 0), ('cumulative_percentage__lte', 100)), name='check_progress_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='progressreport',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='check_progress_period_dates'),
        ),
        migrations.AddIndex(
            model_name='progressstatelog',
            index=models.Index(fields=['progress_report', '-created_at'], name='idx_progress_sl_report_time'),
        ),
        migrations.AddIndex(
            model_name='progressstatelog',
            index=models.Index(fields=['from_state', 'to_state'], name='idx_progress_sl_states'),
        ),
    ]
