"""
RLS policy tests for budgets app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the budgets migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 5 budget tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent table (budgets_budget) uses direct institution_id
- Child tables use subquery (lines/executions/attachments via budget;
  funding sources via project)
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/budgets/specs/budgets/spec.md — Security
Design reference: openspec/changes/budgets/design.md — RLS Policies
Pattern reference: apps/calls/migrations/0002_rls_policies.py

RED PHASE: Tests fail because 0002_rls_policies.py does not exist.
"""

import importlib
import inspect

from apps.budgets.models import (
    Budget,
    BudgetAttachment,
    BudgetExecution,
    BudgetLine,
    FundingSource,
)
from apps.budgets.tests.conftest import (
    BudgetAttachmentFactory,
    BudgetExecutionFactory,
    BudgetFactory,
    BudgetLineFactory,
    FundingSourceFactory,
)
from apps.institutions.tests.conftest import InstitutionFactory
from apps.projects.tests.conftest import ProjectFactory
from tests.rls_helpers import (
    assert_both_visible,
    assert_only_a_visible,
    get_all_sql,
    get_apply_function_source,
    load_migration,
    policy_using,
    set_rls,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "budgets_budget",
    "budgets_budgetline",
    "budgets_fundingsource",
    "budgets_budgetexecution",
    "budgets_budgetattachment",
]

# Tables that traverse a subquery (no direct institution_id column)
CHILD_TABLES = [
    "budgets_budgetline",  # via budget_id
    "budgets_budgetexecution",  # via line_id → budget_id
    "budgets_budgetattachment",  # via budget_id
    "budgets_fundingsource",  # via project_id → project.institution_id
]

# Each child reaches the tenant through its own FK; the map pins the FK column
# and parent table a child's tenant_isolation predicate must traverse.
CHILD_PARENT = {
    "budgets_budgetline": ("budget_id", "budgets_budget"),
    "budgets_budgetexecution": ("line_id", "budgets_budgetline"),
    "budgets_budgetattachment": ("budget_id", "budgets_budget"),
    "budgets_fundingsource": ("project_id", "projects_project"),
}

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/budgets/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("budgets", "0001_initial") in deps, (
            f"Expected dependency on budgets.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython.RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def test_all_expected_tables_in_sql(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert policy_using(sql, table) is not None, (
                f"Table '{table}' missing from RLS migration SQL. All 5 budget tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            predicate = policy_using(sql, table)
            assert predicate is not None, (
                f"'{table}': no CREATE POLICY tenant_isolation with a USING clause"
            )
            assert "sigpi.institution_id" in predicate, (
                f"'{table}': tenant_isolation predicate does not scope by the tenant GUC: "
                f"{predicate!r}"
            )

    def test_superadmin_bypass_policy_per_table(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_table_uses_direct_institution_id(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        predicate = policy_using(sql, "budgets_budget")
        assert predicate is not None, "budgets_budget: no tenant_isolation USING clause"
        assert "institution_id" in predicate, (
            "budgets_budget must use direct institution_id filter. Child tables use subquery."
        )

    def test_child_tables_use_subquery(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        # Lines/attachments reach Budget directly; executions reach Budget via
        # line; funding sources reach Institution via project. Assert each child
        # predicate individually so a single-table regression cannot hide.
        for table, (fk, parent) in CHILD_PARENT.items():
            predicate = policy_using(sql, table)
            assert predicate is not None, f"{table}: no tenant_isolation USING clause"
            assert fk in predicate, (
                f"{table}: tenant_isolation predicate must traverse {fk}: {predicate!r}"
            )
            assert parent in predicate, (
                f"{table}: tenant_isolation predicate must reach {parent}: {predicate!r}"
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow calls/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        migration = load_migration("budgets", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        source = get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────


def _seed_budgets(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="BGA", name="Institution BGA")
    inst_b = InstitutionFactory(code="BGB", name="Institution BGB")
    project_a = ProjectFactory(institution=inst_a)
    project_b = ProjectFactory(institution=inst_b)
    budget_a = BudgetFactory(project=project_a)
    budget_b = BudgetFactory(project=project_b)
    line_a = BudgetLineFactory(budget=budget_a)
    line_b = BudgetLineFactory(budget=budget_b)
    execution_a = BudgetExecutionFactory(line=line_a)
    execution_b = BudgetExecutionFactory(line=line_b)
    attachment_a = BudgetAttachmentFactory(budget=budget_a)
    attachment_b = BudgetAttachmentFactory(budget=budget_b)
    source_a = FundingSourceFactory(project=project_a)
    source_b = FundingSourceFactory(project=project_b)
    set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "budget_a": budget_a,
        "budget_b": budget_b,
        "line_a": line_a,
        "line_b": line_b,
        "execution_a": execution_a,
        "execution_b": execution_b,
        "attachment_a": attachment_a,
        "attachment_b": attachment_b,
        "source_a": source_a,
        "source_b": source_b,
    }


class TestRLSEnforcement:
    """Cross-institution isolation for every protected budgets table."""

    def test_cross_institution_budget_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_budgets(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(Budget, rows["budget_a"].pk, rows["budget_b"].pk)

    def test_cross_institution_line_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_budgets(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(BudgetLine, rows["line_a"].pk, rows["line_b"].pk)

    def test_cross_institution_execution_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_budgets(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(BudgetExecution, rows["execution_a"].pk, rows["execution_b"].pk)

    def test_cross_institution_attachment_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_budgets(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(BudgetAttachment, rows["attachment_a"].pk, rows["attachment_b"].pk)

    def test_cross_institution_funding_source_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_budgets(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(FundingSource, rows["source_a"].pk, rows["source_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_budgets(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=True)
        assert_both_visible(Budget, rows["budget_a"].pk, rows["budget_b"].pk)
        assert_both_visible(BudgetLine, rows["line_a"].pk, rows["line_b"].pk)
        assert_both_visible(BudgetExecution, rows["execution_a"].pk, rows["execution_b"].pk)
        assert_both_visible(BudgetAttachment, rows["attachment_a"].pk, rows["attachment_b"].pk)
        assert_both_visible(FundingSource, rows["source_a"].pk, rows["source_b"].pk)
