"""
RLS policy tests for budgets app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the budgets migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 5 budget tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent table (budgets_budget) uses direct institution_id
- Child tables use subquery (lines/executions/attachments via budget;
  funding sources via project)
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/budgets/specs/budgets/spec.md — Security
Design reference: openspec/changes/budgets/design.md — RLS Policies
Pattern reference: apps/calls/migrations/0002_rls_policies.py

RED PHASE: Tests fail because 0002_rls_policies.py does not exist.
"""

import importlib
import inspect

import pytest
from django.db import connection
from django.db.migrations.loader import MigrationLoader

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "budgets_budget",
    "budgets_budgetline",
    "budgets_fundingsource",
    "budgets_budgetexecution",
    "budgets_budgetattachment",
]

# Tables that traverse a subquery (no direct institution_id column)
CHILD_TABLES = [
    "budgets_budgetline",  # via budget_id
    "budgets_budgetexecution",  # via line_id → budget_id
    "budgets_budgetattachment",  # via budget_id
    "budgets_fundingsource",  # via project_id → project.institution_id
]

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the budgets 0002 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("budgets", "0002_rls_policies")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/budgets/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("budgets", "0001_initial") in deps, (
            f"Expected dependency on budgets.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython.RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. All 5 budget tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_table_uses_direct_institution_id(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "institution_id = current_setting" in sql, (
            "budgets_budget must use direct institution_id filter. Child tables use subquery."
        )

    def test_child_tables_use_subquery(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        # Lines/attachments reach Budget directly; executions reach Budget via
        # line; funding sources reach Institution via project. All subquery the
        # session institution through a parent chain, never a direct column.
        assert "SELECT id FROM budgets_budget" in sql, (
            "Line/attachment/execution child tables must subquery budgets_budget "
            "by institution_id."
        )
        assert "SELECT id FROM projects_project" in sql, (
            "FundingSource must subquery projects_project by institution_id."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow calls/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite)
# ──────────────────────────────────────────────


@pytest.mark.skip(reason="Requires PostgreSQL with RLS support")
class TestRLSEnforcement:
    """Cross-institution isolation tests — PostgreSQL only."""

    def test_cross_institution_budget_invisible(self, db):
        pass

    def test_cross_institution_line_invisible(self, db):
        pass

    def test_cross_institution_execution_invisible(self, db):
        pass

    def test_cross_institution_attachment_invisible(self, db):
        pass

    def test_cross_institution_funding_source_invisible(self, db):
        pass

    def test_superadmin_bypass_sees_all(self, db):
        pass
