# Generated by Django 5.1.15 on 2026-06-19 19:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0004_alter_facultad_status_alter_institution_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=30)),
                ('document_number', models.CharField(max_length=30)),
                ('primary_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('academic_formation', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchers', to='institutions.institution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Researcher',
                'verbose_name_plural': 'Researchers',
                'db_table': 'researchers_researcher',
                'ordering': ['institution', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('cvlac', 'CvLAC'), ('orcid', 'ORCID'), ('google_scholar', 'Google Scholar'), ('linkedin', 'LinkedIn'), ('researchgate', 'ResearchGate')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_profiles', to='researchers.researcher')),
            ],
            options={
                'verbose_name': 'External Profile',
                'verbose_name_plural': 'External Profiles',
                'db_table': 'researchers_externalprofile',
                'ordering': ['researcher', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_affiliations', to='institutions.researchcenter')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_affiliations', to='institutions.researchgroup')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_affiliations', to='institutions.researchline')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='researchers.researcher')),
            ],
            options={
                'verbose_name': 'Researcher Affiliation',
                'verbose_name_plural': 'Researcher Affiliations',
                'db_table': 'researchers_researcheraffiliation',
                'ordering': ['researcher', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cv', 'Curriculum Vitae'), ('certificate', 'Certificate'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('external_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='researchers.researcher')),
            ],
            options={
                'verbose_name': 'Researcher Attachment',
                'verbose_name_plural': 'Researcher Attachments',
                'db_table': 'researchers_researcherattachment',
                'ordering': ['researcher', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researcher',
            index=models.Index(fields=['institution', 'is_active'], name='idx_researcher_inst_active'),
        ),
        migrations.AddConstraint(
            model_name='researcher',
            constraint=models.UniqueConstraint(fields=('institution', 'document_number'), name='unique_document_per_institution'),
        ),
    ]
