# Generated by Django 5.1.15 on 2026-06-18 16:13
"""Seed the 7 fixed SIGPI roles. See design.md Role model for hierarchy."""

from django.db import migrations

ROLES = [
    ("Superadmin", "sigpi_superadmin", 1),
    ("Admin Institucional", "sigpi_admin", 2),
    ("Director de Centro", "sigpi_center_director", 3),
    ("Investigador", "sigpi_researcher", 4),
    ("Evaluador", "sigpi_evaluator", 5),
    ("Asistente", "sigpi_assistant", 6),
    ("Auditor", "sigpi_auditor", 7),
]


def create_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    for name, kc_name, level in ROLES:
        Role.objects.get_or_create(
            name=name,
            defaults={"keycloak_role_name": kc_name, "level": level},
        )


def remove_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    names = [name for name, _, _ in ROLES]
    Role.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]
    operations = [
        migrations.RunPython(create_roles, reverse_code=remove_roles),
    ]
