# Generated by Django 6.0.6 on 2026-06-18 17:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('INSTITUTION_SWITCH', 'Institution Switch'), ('ROLE_CHANGE', 'Role Change'), ('PERMISSION_DENIED', 'Permission Denied')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('institution_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'db_table': 'accounts_auditevent',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='accounts_au_event_t_784a60_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_d1146d_idx')],
            },
        ),
    ]
