# Generated by Django 5.1.15 on 2026-08-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('INSTITUTION_SWITCH', 'Institution Switch'), ('ROLE_CHANGE', 'Role Change'), ('PERMISSION_DENIED', 'Permission Denied'), ('PROGRESS_STATE_CHANGE', 'Progress State Change'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_APPROVED', 'Report Approved'), ('BUDGET_CREATED', 'Budget Created'), ('BUDGET_UPDATED', 'Budget Updated'), ('BUDGET_EXECUTION_ADDED', 'Budget Execution Added')], db_index=True, max_length=50),
        ),
    ]
