# Generated by Django 6.0.7 on 2026-08-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("INSTITUTION_SWITCH", "Institution Switch"),
                    ("ROLE_CHANGE", "Role Change"),
                    ("PERMISSION_DENIED", "Permission Denied"),
                    ("PROGRESS_STATE_CHANGE", "Progress State Change"),
                    ("REPORT_GENERATED", "Report Generated"),
                    ("REPORT_APPROVED", "Report Approved"),
                    ("BUDGET_CREATED", "Budget Created"),
                    ("BUDGET_UPDATED", "Budget Updated"),
                    ("BUDGET_EXECUTION_ADDED", "Budget Execution Added"),
                    ("DOCUMENT_UPLOADED", "Document Uploaded"),
                    ("DOCUMENT_SIGNED", "Document Signed"),
                    ("MINUTES_CREATED", "Minutes Created"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
