# Generated by Django 6.0.7 on 2026-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="action",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="entity_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="entity_type",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="new_values",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="old_values",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="project_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("INSTITUTION_SWITCH", "Institution Switch"),
                    ("ROLE_CHANGE", "Role Change"),
                    ("PERMISSION_DENIED", "Permission Denied"),
                    ("PROGRESS_STATE_CHANGE", "Progress State Change"),
                    ("REPORT_GENERATED", "Report Generated"),
                    ("REPORT_APPROVED", "Report Approved"),
                    ("BUDGET_CREATED", "Budget Created"),
                    ("BUDGET_UPDATED", "Budget Updated"),
                    ("BUDGET_EXECUTION_ADDED", "Budget Execution Added"),
                    ("DOCUMENT_UPLOADED", "Document Uploaded"),
                    ("DOCUMENT_SIGNED", "Document Signed"),
                    ("MINUTES_CREATED", "Minutes Created"),
                    ("CREATE", "Created"),
                    ("UPDATE", "Updated"),
                    ("DELETE", "Deleted"),
                    ("STATE_CHANGE", "State Changed"),
                    ("DOCUMENT_DOWNLOADED", "Document Downloaded"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="accounts_au_entity__85e73d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["project_id", "-timestamp"], name="accounts_au_project_1658e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "-timestamp"], name="accounts_au_action_dcb88a_idx"
            ),
        ),
    ]
