"""
RLS policy tests for researchers app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the researchers migrations module
- Contains a RunPython operation
- Depends on 0001_initial
- SQL targets all 4 researcher tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent tables (Researcher) use direct institution_id
- Child tables (Affiliation, Profile, Attachment) use subquery via researcher_id
- PostgreSQL-only guard (no-op on SQLite)

Spec reference: openspec/changes/researchers/spec.md — Security Requirements
Design reference: openspec/changes/researchers/design.md — RLS Policies
Pattern reference: institutions/0003_rls_policies.py

RED PHASE: Tests fail because 0002_rls_policies.py does not exist.
"""

import importlib
import inspect

from django.db import connection
from django.db.migrations.loader import MigrationLoader

from apps.institutions.tests.conftest import InstitutionFactory
from apps.researchers.models import (
    ExternalProfile,
    Researcher,
    ResearcherAffiliation,
    ResearcherAttachment,
)
from apps.researchers.tests.conftest import (
    ExternalProfileFactory,
    ResearcherAffiliationFactory,
    ResearcherAttachmentFactory,
    ResearcherFactory,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "researchers_researcher",
    "researchers_researcheraffiliation",
    "researchers_externalprofile",
    "researchers_researcherattachment",
]

# Child tables that use a subquery (no direct institution_id)
CHILD_TABLES = [
    "researchers_researcheraffiliation",
    "researchers_externalprofile",
    "researchers_researcherattachment",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the researchers 0002 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("researchers", "0002_rls_policies")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        """Migration 0002_rls_policies must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/researchers/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        """Migration 0002 must depend on 0001_initial."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("researchers", "0001_initial") in deps, (
            f"Expected dependency on researchers.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython.RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        """Collect all SQL from the migration module."""
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have RLS policies in the migration SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. "
                f"All 4 researcher tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table must have a tenant_isolation policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_table_uses_direct_institution_id(self, db):
        """Researcher table must filter by institution_id directly (has the column)."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        # Parent table should use direct institution_id
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), "Researcher table must use direct institution_id filter. Child tables use subquery."

    def test_child_tables_use_subquery(self, db):
        """Child tables must filter via subquery through researcher_id."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in CHILD_TABLES:
            # Child tables should reference researchers_researcher in a subquery
            assert "researcher_id IN" in sql or "researchers_researcher" in sql, (
                f"Child table '{table}' must use a subquery through "
                f"researcher_id → researchers_researcher.institution_id. "
                f"Child tables have no direct institution_id column."
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow institutions/0003 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────

TENANT_GUC = "sigpi.institution_id"
BYPASS_GUC = "sigpi.bypass_rls"


def _set_rls(conn, institution_id, bypass):
    """Write the RLS GUCs at connection scope, exactly like production does."""
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [TENANT_GUC, "" if institution_id is None else str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [BYPASS_GUC, "true" if bypass else "false"],
        )


def _seed_researchers(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    _set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="BGA", name="Institution BGA")
    inst_b = InstitutionFactory(code="BGB", name="Institution BGB")
    researcher_a = ResearcherFactory(institution=inst_a)
    researcher_b = ResearcherFactory(institution=inst_b)
    # ResearcherAffiliation.save() runs full_clean(): the affiliation must
    # point at a same-institution center and must not be primary.
    affiliation_a = ResearcherAffiliationFactory(researcher=researcher_a, is_primary=False)
    affiliation_b = ResearcherAffiliationFactory(researcher=researcher_b, is_primary=False)
    profile_a = ExternalProfileFactory(researcher=researcher_a)
    profile_b = ExternalProfileFactory(researcher=researcher_b)
    attachment_a = ResearcherAttachmentFactory(researcher=researcher_a)
    attachment_b = ResearcherAttachmentFactory(researcher=researcher_b)
    _set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "researcher_a": researcher_a,
        "researcher_b": researcher_b,
        "affiliation_a": affiliation_a,
        "affiliation_b": affiliation_b,
        "profile_a": profile_a,
        "profile_b": profile_b,
        "attachment_a": attachment_a,
        "attachment_b": attachment_b,
    }


def _assert_only_a_visible(model, pk_a, pk_b):
    """Non-vacuous assertion pair: A's row visible, B's row denied."""
    assert model.objects.filter(pk=pk_a).exists(), (
        f"{model.__name__}: institution A's seeded row is not visible under "
        f"institution A's tenant context."
    )
    assert model.objects.filter(pk=pk_b).count() == 0, (
        f"{model.__name__}: institution B's seeded row leaked into institution A's tenant context."
    )


def _assert_both_visible(model, pk_a, pk_b):
    """Bypass must reveal both institutions' rows, not merely zero rows."""
    both = model.objects.filter(pk__in=[pk_a, pk_b]).count()
    assert both == 2, (
        f"{model.__name__}: superadmin bypass exposed {both} of 2 seeded rows; "
        f"it must reveal more than a single tenant scope."
    )


class TestRLSEnforcement:
    """Cross-institution isolation for every protected researchers table."""

    def test_cross_institution_researcher_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_researchers(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(Researcher, rows["researcher_a"].pk, rows["researcher_b"].pk)

    def test_cross_institution_affiliation_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_researchers(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(
            ResearcherAffiliation, rows["affiliation_a"].pk, rows["affiliation_b"].pk
        )

    def test_cross_institution_externalprofile_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_researchers(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ExternalProfile, rows["profile_a"].pk, rows["profile_b"].pk)

    def test_cross_institution_attachment_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_researchers(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(
            ResearcherAttachment, rows["attachment_a"].pk, rows["attachment_b"].pk
        )

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_researchers(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=True)
        _assert_both_visible(Researcher, rows["researcher_a"].pk, rows["researcher_b"].pk)
        _assert_both_visible(
            ResearcherAffiliation, rows["affiliation_a"].pk, rows["affiliation_b"].pk
        )
        _assert_both_visible(ExternalProfile, rows["profile_a"].pk, rows["profile_b"].pk)
        _assert_both_visible(ResearcherAttachment, rows["attachment_a"].pk, rows["attachment_b"].pk)
