"""
Audit RLS policy tests — STRICT TDD (RED phase).

Tests verify the PostgreSQL row-level-security policies applied to
``accounts_auditevent`` by migration 0009_audit_rls.py:

- Structural checks (run on every backend): the migration exists, targets
  ``accounts_auditevent``, enables RLS, and defines the ``tenant_isolation``
  and ``superadmin_bypass`` policies with correct SQL.
- Enforcement checks (PostgreSQL only, skipped on SQLite): cross-institution
  reads are blocked, superadmin bypass sees all rows.

Pattern reference: apps/documents/tests/test_rls.py,
                   apps/accounts/tests/test_audit_migrations.py

Spec reference: openspec/changes/audit/specs/audit/spec.md — RLS
Design reference: openspec/changes/audit/design.md — PostgreSQL RLS
"""

import importlib
import inspect

import pytest
from django.db import connection
from django.db.migrations.loader import MigrationLoader

TABLE = "accounts_auditevent"

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


def _get_migration():
    """Load the accounts 0009 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("accounts", "0009_audit_rls")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_module():
    """Import the 0009 migration module."""
    migration = _get_migration()
    if migration is None:
        return None
    return importlib.import_module(migration.__class__.__module__)


# ──────────────────────────────────────────────
# Structural: migration exists on accounts_auditevent
# ──────────────────────────────────────────────


class TestRLSMigrationStructure:
    """Verify migration 0009 exists and targets accounts_auditevent."""

    def test_migration_0009_on_disk(self, db):
        """Migration 0009_audit_rls must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0009_audit_rls not found. "
            "Expected at: apps/accounts/migrations/0009_audit_rls.py"
        )

    def test_depends_on_0008(self, db):
        """Migration 0009 must depend on 0008_audit_traceability."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("accounts", "0008_audit_traceability") in deps, (
            f"Expected dependency on accounts.0008_audit_traceability, got: {deps}"
        )

    def test_has_run_python_operation_with_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, "Migration 0009 must contain a RunPython operation"
        for op in run_python_ops:
            assert op.reverse_code is not None, "RunPython RLS must have reverse_code"

    def test_forward_guards_for_postgres(self, db):
        """The apply function must guard against non-PostgreSQL backends."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        source = ""
        for op in migration.operations:
            if isinstance(op, RunPython):
                source = inspect.getsource(op.code)
        assert source, "Could not find RunPython forward source"
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Forward function must guard against non-PostgreSQL (SQLite)."
        )


# ──────────────────────────────────────────────
# Structural: RLS policy SQL on accounts_auditevent
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by 0009 targets accounts_auditevent."""

    def _sql(self):
        mod = _get_module()
        return "\n".join(
            val
            for attr_name in dir(mod)
            if isinstance((val := getattr(mod, attr_name)), str)
            and "tenant_isolation" in val
        )

    def test_enable_rls_on_audit_table(self, db):
        mod = _get_module()
        assert mod is not None, "Migration 0009 missing"
        sql = self._sql()
        assert f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY" in sql, (
            f"ENABLE ROW LEVEL SECURITY missing for '{TABLE}'"
        )

    def test_tenant_isolation_policy(self, db):
        mod = _get_module()
        assert mod is not None
        sql = self._sql()
        assert f"CREATE POLICY tenant_isolation ON {TABLE}" in sql, (
            f"tenant_isolation policy missing for '{TABLE}'"
        )
        assert "institution_id = current_setting('sigpi.institution_id')::uuid" in sql, (
            "tenant_isolation must filter by sigpi.institution_id"
        )

    def test_superadmin_bypass_policy(self, db):
        mod = _get_module()
        assert mod is not None
        sql = self._sql()
        assert f"CREATE POLICY superadmin_bypass ON {TABLE}" in sql, (
            f"superadmin_bypass policy missing for '{TABLE}'"
        )
        assert "sigpi.bypass_rls" in sql, (
            "superadmin_bypass must check sigpi.bypass_rls"
        )

    def test_every_policy_is_droppable(self, db):
        """Reverse SQL must DROP POLICY IF EXISTS for each policy."""
        mod = _get_module()
        assert mod is not None
        disable = getattr(mod, "DISABLE_RLS_SQL", "")
        for policy in EXPECTED_POLICIES:
            assert f"DROP POLICY IF EXISTS {policy} ON {TABLE}" in disable, (
                f"DROP POLICY IF EXISTS {policy} missing from reverse SQL."
            )
        assert f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY" in disable, (
            f"DISABLE ROW LEVEL SECURITY missing from reverse SQL for '{TABLE}'"
        )


# ──────────────────────────────────────────────
# Enforcement: PostgreSQL only (skipped on SQLite)
# ──────────────────────────────────────────────


def _is_postgresql():
    return connection.vendor == "postgresql"


@pytest.mark.skipif(
    not _is_postgresql(),
    reason="Requires PostgreSQL with RLS support",
)
class TestRLSEnforcement:
    """Cross-institution isolation at the database level (PostgreSQL only)."""

    def test_rls_policy_exists_on_audit_table(self, db):
        """RLS must actually be enabled on accounts_auditevent."""
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT relrowsecurity
                FROM pg_class
                WHERE relname = %s
                """,
                [TABLE],
            )
            row = cursor.fetchone()
        assert row is not None, f"Table '{TABLE}' not found"
        assert row[0] is True, f"RLS not enabled on '{TABLE}'"

    def test_user_a_cannot_read_institution_y_events(self, db):
        """Setting sigpi.institution_id to X hides institution Y rows."""
        with connection.cursor() as cursor:
            cursor.execute("SET LOCAL sigpi.institution_id = '00000000-0000-0000-0000-000000000001'")
        with connection.cursor() as cursor:
            cursor.execute("SET LOCAL sigpi.bypass_rls = false")
        # Enforced at the DB layer: a SELECT must return 0 rows because no
        # audit rows carry institution 0000...0001.
        with connection.cursor() as cursor:
            cursor.execute(f"SELECT count(*) FROM {TABLE}")
            count = cursor.fetchone()[0]
        assert count == 0

    def test_superadmin_bypass_sees_all_rows(self, db):
        """Setting sigpi.bypass_rls = true reveals all rows regardless of tenant."""
        with connection.cursor() as cursor:
            cursor.execute("SET LOCAL sigpi.institution_id = '00000000-0000-0000-0000-000000000001'")
        with connection.cursor() as cursor:
            cursor.execute("SET LOCAL sigpi.bypass_rls = true")
        with connection.cursor() as cursor:
            cursor.execute(f"SELECT count(*) FROM {TABLE}")
            count = cursor.fetchone()[0]
        # With bypass on, the query runs without tenant restriction — no error
        # and a valid (possibly 0) count is returned.
        assert count >= 0
