"""
Audit RLS policy tests — STRICT TDD (RED phase).

Tests verify the PostgreSQL row-level-security policies applied to
``accounts_auditevent`` by migration 0009_audit_rls.py:

- Structural checks (run on every backend): the migration exists, targets
  ``accounts_auditevent``, enables RLS, and defines the ``tenant_isolation``
  and ``superadmin_bypass`` policies with correct SQL.
- Enforcement checks (PostgreSQL only, skipped on SQLite): cross-institution
  reads are blocked, superadmin bypass sees all rows.

Pattern reference: apps/documents/tests/test_rls.py,
                   apps/accounts/tests/test_audit_migrations.py

Spec reference: openspec/changes/audit/specs/audit/spec.md — RLS
Design reference: openspec/changes/audit/design.md — PostgreSQL RLS
"""

import importlib
import inspect
import uuid

import pytest
from django.db import DatabaseError, connection, transaction
from django.db.migrations.loader import MigrationLoader

TABLE = "accounts_auditevent"

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


def _get_migration():
    """Load the accounts 0009 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("accounts", "0009_audit_rls")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_module():
    """Import the 0009 migration module."""
    migration = _get_migration()
    if migration is None:
        return None
    return importlib.import_module(migration.__class__.__module__)


# ──────────────────────────────────────────────
# Structural: migration exists on accounts_auditevent
# ──────────────────────────────────────────────


class TestRLSMigrationStructure:
    """Verify migration 0009 exists and targets accounts_auditevent."""

    def test_migration_0009_on_disk(self, db):
        """Migration 0009_audit_rls must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0009_audit_rls not found. "
            "Expected at: apps/accounts/migrations/0009_audit_rls.py"
        )

    def test_depends_on_0008(self, db):
        """Migration 0009 must depend on 0008_audit_traceability."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("accounts", "0008_audit_traceability") in deps, (
            f"Expected dependency on accounts.0008_audit_traceability, got: {deps}"
        )

    def test_has_run_python_operation_with_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, "Migration 0009 must contain a RunPython operation"
        for op in run_python_ops:
            assert op.reverse_code is not None, "RunPython RLS must have reverse_code"

    def test_forward_guards_for_postgres(self, db):
        """The apply function must guard against non-PostgreSQL backends."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        source = ""
        for op in migration.operations:
            if isinstance(op, RunPython):
                source = inspect.getsource(op.code)
        assert source, "Could not find RunPython forward source"
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Forward function must guard against non-PostgreSQL (SQLite)."
        )


# ──────────────────────────────────────────────
# Structural: RLS policy SQL on accounts_auditevent
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by 0009 targets accounts_auditevent."""

    def _sql(self):
        mod = _get_module()
        return "\n".join(
            val
            for attr_name in dir(mod)
            if isinstance((val := getattr(mod, attr_name)), str) and "tenant_isolation" in val
        )

    def test_enable_rls_on_audit_table(self, db):
        mod = _get_module()
        assert mod is not None, "Migration 0009 missing"
        sql = self._sql()
        assert f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY" in sql, (
            f"ENABLE ROW LEVEL SECURITY missing for '{TABLE}'"
        )

    def test_tenant_isolation_policy(self, db):
        mod = _get_module()
        assert mod is not None
        sql = self._sql()
        assert f"CREATE POLICY tenant_isolation ON {TABLE}" in sql, (
            f"tenant_isolation policy missing for '{TABLE}'"
        )
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), "tenant_isolation must filter by sigpi.institution_id"

    def test_superadmin_bypass_policy(self, db):
        mod = _get_module()
        assert mod is not None
        sql = self._sql()
        assert f"CREATE POLICY superadmin_bypass ON {TABLE}" in sql, (
            f"superadmin_bypass policy missing for '{TABLE}'"
        )
        assert "sigpi.bypass_rls" in sql, "superadmin_bypass must check sigpi.bypass_rls"

    def test_every_policy_is_droppable(self, db):
        """Reverse SQL must DROP POLICY IF EXISTS for each policy."""
        mod = _get_module()
        assert mod is not None
        disable = getattr(mod, "DISABLE_RLS_SQL", "")
        for policy in EXPECTED_POLICIES:
            assert f"DROP POLICY IF EXISTS {policy} ON {TABLE}" in disable, (
                f"DROP POLICY IF EXISTS {policy} missing from reverse SQL."
            )
        assert f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY" in disable, (
            f"DISABLE ROW LEVEL SECURITY missing from reverse SQL for '{TABLE}'"
        )


# ──────────────────────────────────────────────
# Enforcement: PostgreSQL only (skipped on SQLite)
# ──────────────────────────────────────────────


@pytest.mark.usefixtures("postgres_app_role")
class TestRLSEnforcement:
    """Cross-institution isolation at the database level (PostgreSQL only)."""

    def test_rls_policy_exists_on_audit_table(self, db):
        """RLS must actually be enabled on accounts_auditevent."""
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT relrowsecurity
                FROM pg_class
                WHERE relname = %s
                """,
                [TABLE],
            )
            row = cursor.fetchone()
        assert row is not None, f"Table '{TABLE}' not found"
        assert row[0] is True, f"RLS not enabled on '{TABLE}'"

    def test_user_a_cannot_read_institution_y_events(self, postgres_app_role):
        """A tenant scoped to X sees X's row and not Y's seeded row.

        The original body counted an empty table, so ``count == 0`` held no
        matter what the policy did. This seeds real rows for both tenants
        under bypass and proves the pair: X's row is visible to X, Y's is not.
        """
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=True)
        row_x = uuid.uuid4()
        row_y = uuid.uuid4()
        _insert_audit(conn, row_x, institution_id=INSTITUTION_A)
        _insert_audit(conn, row_y, institution_id=INSTITUTION_B)

        _set_context(conn, INSTITUTION_A, bypass=False)

        assert _count_row(conn, row_x) == 1, "Institution X could not read its own audit row."
        assert _count_row(conn, row_y) == 0, (
            "Institution X read institution Y's audit row: tenant isolation is "
            "not enforced on accounts_auditevent."
        )

    def test_superadmin_bypass_sees_all_rows(self, postgres_app_role):
        """Bypass reveals strictly more than the tenant context.

        The original body ended on ``assert count >= 0`` — true for every
        possible outcome. This seeds one row per institution and requires the
        tenant scope to reveal one while bypass reveals both.
        """
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=True)
        row_a = uuid.uuid4()
        row_b = uuid.uuid4()
        _insert_audit(conn, row_a, institution_id=INSTITUTION_A)
        _insert_audit(conn, row_b, institution_id=INSTITUTION_B)

        _set_context(conn, INSTITUTION_A, bypass=False)
        tenant_visible = _count_row(conn, row_a) + _count_row(conn, row_b)
        assert tenant_visible == 1, (
            f"Tenant A saw {tenant_visible} of the 2 seeded rows; the tenant "
            f"scope must hide institution B's row."
        )

        _set_context(conn, INSTITUTION_A, bypass=True)
        bypass_visible = _count_row(conn, row_a) + _count_row(conn, row_b)
        assert bypass_visible == 2, (
            f"Superadmin bypass saw {bypass_visible} of the 2 seeded rows; it "
            f"must reveal both institutions."
        )
        assert bypass_visible > tenant_visible, (
            "Bypass did not reveal more rows than the tenant context."
        )


# ──────────────────────────────────────────────
# Per-command policies introduced by accounts/0011_audit_policy_per_command
# ──────────────────────────────────────────────

INSTITUTION_A = "00000000-0000-0000-0000-0000000000a1"
INSTITUTION_B = "00000000-0000-0000-0000-0000000000b1"


def _set_context(conn, institution_id, bypass=False):
    """Scope the RLS GUCs to the current test transaction (rolled back with it)."""
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT set_config('sigpi.institution_id', %s, true)",
            ["" if institution_id is None else str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config('sigpi.bypass_rls', %s, true)",
            ["true" if bypass else "false"],
        )


def _insert_audit(conn, row_id, institution_id):
    """Append one audit row directly, exercising the INSERT policy."""
    with conn.cursor() as cursor:
        cursor.execute(
            "INSERT INTO accounts_auditevent (id, event_type, timestamp, institution_id) "
            "VALUES (%s, %s, now(), %s)",
            [str(row_id), "LOGIN", None if institution_id is None else str(institution_id)],
        )


def _count_row(conn, row_id):
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT count(*) FROM accounts_auditevent WHERE id = %s",
            [str(row_id)],
        )
        return cursor.fetchone()[0]


class TestAuditPerCommandEnforcement:
    """Per-command RLS on accounts_auditevent — real PostgreSQL (skipped on SQLite).

    Verified against migration ``accounts/0011_audit_policy_per_command``:

    - ``tenant_isolation`` is SELECT-only and tenant-scoped;
    - ``tenant_insert`` accepts system events with no institution;
    - an INSERT claiming a foreign institution is rejected;
    - UPDATE/DELETE have no applicable tenant policy, so the table is append-only.
    """

    def test_insert_with_null_institution_succeeds(self, postgres_app_role):
        """A system event (failed login, logout) carries no tenant and must append."""
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=False)
        row_id = uuid.uuid4()

        _insert_audit(conn, row_id, institution_id=None)

        # The row is invisible to the tenant, so confirm it persisted under bypass.
        _set_context(conn, INSTITUTION_A, bypass=True)
        assert _count_row(conn, row_id) == 1

    def test_insert_claiming_another_institution_fails(self, postgres_app_role):
        """A row cannot be appended under another institution's identity."""
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=False)
        row_id = uuid.uuid4()

        with pytest.raises(DatabaseError):
            with transaction.atomic():
                _insert_audit(conn, row_id, institution_id=INSTITUTION_B)

    def test_tenant_cannot_select_null_institution_row(self, postgres_app_role):
        """A row with no institution is never visible to a tenant session."""
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=True)
        row_id = uuid.uuid4()
        _insert_audit(conn, row_id, institution_id=None)

        _set_context(conn, INSTITUTION_A, bypass=False)
        assert _count_row(conn, row_id) == 0

    def test_tenant_can_select_own_institution_rows(self, postgres_app_role):
        """A tenant session sees its own institution's rows."""
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=True)
        row_id = uuid.uuid4()
        _insert_audit(conn, row_id, institution_id=INSTITUTION_A)

        _set_context(conn, INSTITUTION_A, bypass=False)
        assert _count_row(conn, row_id) == 1

    def test_update_is_denied_for_app_role(self, postgres_app_role):
        """No tenant policy applies to UPDATE — the row cannot be modified."""
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=True)
        row_id = uuid.uuid4()
        _insert_audit(conn, row_id, institution_id=INSTITUTION_A)

        _set_context(conn, INSTITUTION_A, bypass=False)
        with conn.cursor() as cursor:
            cursor.execute(
                "UPDATE accounts_auditevent SET event_type = 'LOGOUT' WHERE id = %s",
                [str(row_id)],
            )
            updated = cursor.rowcount

        assert updated == 0, "A tenant session was able to UPDATE an audit row (not append-only)."
        _set_context(conn, INSTITUTION_A, bypass=True)
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT event_type FROM accounts_auditevent WHERE id = %s",
                [str(row_id)],
            )
            assert cursor.fetchone()[0] == "LOGIN"

    def test_delete_is_denied_for_app_role(self, postgres_app_role):
        """No tenant policy applies to DELETE — the row cannot be removed."""
        conn = postgres_app_role
        _set_context(conn, INSTITUTION_A, bypass=True)
        row_id = uuid.uuid4()
        _insert_audit(conn, row_id, institution_id=INSTITUTION_A)

        _set_context(conn, INSTITUTION_A, bypass=False)
        with conn.cursor() as cursor:
            cursor.execute(
                "DELETE FROM accounts_auditevent WHERE id = %s",
                [str(row_id)],
            )
            deleted = cursor.rowcount

        assert deleted == 0, "A tenant session was able to DELETE an audit row (not append-only)."
        _set_context(conn, INSTITUTION_A, bypass=True)
        assert _count_row(conn, row_id) == 1
