"""
RLS policy tests for the progress (advances) app.

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the progress migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 4 progress tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent table (progress_progressreport) uses direct institution_id
- Child tables (review/document/state log) use a subquery via progress_report_id
- PostgreSQL-only guard (no-op on SQLite)

The enforcement tests run on a real PostgreSQL connection assumed as the
least-privilege ``sigpi_app`` role (via the ``postgres_app_role`` fixture), so
row-level security genuinely applies. They seed one row per institution for
the parent report and every child table under a bypass context, then prove
institution A's rows are visible while institution B's stay denied, and that
the superadmin bypass reveals both. The parent/child pair is covered together:
the child tables only resolve the session institution through their report.

Design reference: openspec/sdd/advances/design.md — RLS Policies
Pattern reference: apps/budgets/tests/test_rls.py
"""

import importlib
import inspect

from apps.institutions.tests.conftest import InstitutionFactory
from apps.progress.models import (
    ProgressDocument,
    ProgressReport,
    ProgressReview,
    ProgressStateLog,
)
from apps.progress.tests.conftest import (
    ProgressDocumentFactory,
    ProgressReportFactory,
    ProgressReviewFactory,
    ProgressStateLogFactory,
)
from tests.rls_helpers import (
    assert_both_visible,
    assert_only_a_visible,
    get_all_sql,
    get_apply_function_source,
    load_migration,
    policy_using,
    set_rls,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "progress_progressreport",
    "progress_progressreview",
    "progress_progressdocument",
    "progress_progressstatelog",
]

# Tables that traverse a subquery (no direct institution_id column)
CHILD_TABLES = [
    "progress_progressreview",  # via progress_report_id
    "progress_progressdocument",  # via progress_report_id
    "progress_progressstatelog",  # via progress_report_id
]

# Each child reaches the tenant through progress_report_id into the report.
CHILD_PARENT = {
    "progress_progressreview": ("progress_report_id", "progress_progressreport"),
    "progress_progressdocument": ("progress_report_id", "progress_progressreport"),
    "progress_progressstatelog": ("progress_report_id", "progress_progressreport"),
}

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/progress/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("progress", "0001_initial") in deps, (
            f"Expected dependency on progress.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def test_all_expected_tables_in_sql(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert policy_using(sql, table) is not None, (
                f"Table '{table}' missing from RLS migration SQL. "
                f"All 4 progress tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            predicate = policy_using(sql, table)
            assert predicate is not None, (
                f"'{table}': no CREATE POLICY tenant_isolation with a USING clause"
            )
            assert "sigpi.institution_id" in predicate, (
                f"'{table}': tenant_isolation predicate does not scope by the tenant GUC: "
                f"{predicate!r}"
            )

    def test_superadmin_bypass_policy_per_table(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_table_uses_direct_institution_id(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        predicate = policy_using(sql, "progress_progressreport")
        assert predicate is not None, "progress_progressreport: no tenant_isolation USING clause"
        assert "institution_id" in predicate, (
            "progress_progressreport must use direct institution_id filter. Child tables use subquery."
        )

    def test_child_tables_use_subquery(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        # Review/document/state log reach Institution through the parent report.
        for table, (fk, parent) in CHILD_PARENT.items():
            predicate = policy_using(sql, table)
            assert predicate is not None, f"{table}: no tenant_isolation USING clause"
            assert fk in predicate and parent in predicate, (
                f"{table}: predicate must subquery {parent} via {fk}: {predicate!r}"
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow the sibling-app pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        migration = load_migration("progress", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        source = get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────


def _seed_progress(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="PGA", name="Institution PGA")
    inst_b = InstitutionFactory(code="PGB", name="Institution PGB")
    report_a = ProgressReportFactory(institution=inst_a)
    report_b = ProgressReportFactory(institution=inst_b)
    review_a = ProgressReviewFactory(progress_report=report_a)
    review_b = ProgressReviewFactory(progress_report=report_b)
    document_a = ProgressDocumentFactory(progress_report=report_a)
    document_b = ProgressDocumentFactory(progress_report=report_b)
    log_a = ProgressStateLogFactory(progress_report=report_a)
    log_b = ProgressStateLogFactory(progress_report=report_b)
    set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "report_a": report_a,
        "report_b": report_b,
        "review_a": review_a,
        "review_b": review_b,
        "document_a": document_a,
        "document_b": document_b,
        "log_a": log_a,
        "log_b": log_b,
    }


class TestRLSEnforcement:
    """Cross-institution isolation for the report and every child table."""

    def test_cross_institution_report_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_progress(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(ProgressReport, rows["report_a"].pk, rows["report_b"].pk)

    def test_cross_institution_review_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_progress(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(ProgressReview, rows["review_a"].pk, rows["review_b"].pk)

    def test_cross_institution_document_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_progress(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(ProgressDocument, rows["document_a"].pk, rows["document_b"].pk)

    def test_cross_institution_state_log_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_progress(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(ProgressStateLog, rows["log_a"].pk, rows["log_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_progress(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=True)
        assert_both_visible(ProgressReport, rows["report_a"].pk, rows["report_b"].pk)
        assert_both_visible(ProgressReview, rows["review_a"].pk, rows["review_b"].pk)
        assert_both_visible(ProgressDocument, rows["document_a"].pk, rows["document_b"].pk)
        assert_both_visible(ProgressStateLog, rows["log_a"].pk, rows["log_b"].pk)
