# Generated by Django 5.1.15 on 2026-08-24 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0004_alter_facultad_status_alter_institution_status_and_more'),
        ('projects', '0003_project_cumulative_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('executed', 'Executed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='institutions.institution')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='projects.project')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budgets_budget',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=50)),
                ('external_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='budgets.budget')),
            ],
            options={
                'verbose_name': 'Budget Attachment',
                'verbose_name_plural': 'Budget Attachments',
                'db_table': 'budgets_budgetattachment',
                'ordering': ['budget', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgets.budget')),
            ],
            options={
                'verbose_name': 'Budget Line',
                'verbose_name_plural': 'Budget Lines',
                'db_table': 'budgets_budgetline',
                'ordering': ['budget', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('executed_at', models.DateField()),
                ('authorized_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_executions_authorized', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='budgets.budgetline')),
            ],
            options={
                'verbose_name': 'Budget Execution',
                'verbose_name_plural': 'Budget Executions',
                'db_table': 'budgets_budgetexecution',
                'ordering': ['line', '-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_sources', to='projects.project')),
            ],
            options={
                'verbose_name': 'Funding Source',
                'verbose_name_plural': 'Funding Sources',
                'db_table': 'budgets_fundingsource',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['institution', 'status'], name='idx_budget_inst_status'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__gte', 0)), name='check_budget_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('project',), name='unique_budget_per_project'),
        ),
        migrations.AddIndex(
            model_name='budgetattachment',
            index=models.Index(fields=['budget'], name='idx_budgetattachment_budget'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget'], name='idx_budgetline_budget'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'name'], name='idx_budgetline_budget_name'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__gte', 0)), name='check_budgetline_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['line', 'executed_at'], name='idx_budgetexec_line_exec'),
        ),
        migrations.AddConstraint(
            model_name='budgetexecution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='check_budgetexecution_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='fundingsource',
            index=models.Index(fields=['project'], name='idx_fundingsource_project'),
        ),
        migrations.AddConstraint(
            model_name='fundingsource',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='check_fundingsource_amount_non_negative'),
        ),
    ]
