# Generated by Django 6.0.7 on 2026-08-24 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_document_types(apps, schema_editor):
    """Insert the 12 fixed DocumentType rows from SPEC §6.7 (RF-D08)."""
    from apps.documents.models import DOCUMENT_TYPES

    DocumentType = apps.get_model("documents", "DocumentType")
    DocumentType.objects.bulk_create(
        [DocumentType(code=code, label=label) for code, label in DOCUMENT_TYPES]
    )


def unseed_document_types(apps, schema_editor):
    """Reverse: remove the 12 seeded DocumentType rows."""
    from apps.documents.models import DOCUMENT_TYPES

    DocumentType = apps.get_model("documents", "DocumentType")
    DocumentType.objects.filter(code__in=[code for code, _ in DOCUMENT_TYPES]).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calls", "0002_rls_policies"),
        ("institutions", "0004_alter_facultad_status_alter_institution_status_and_more"),
        ("products", "0001_initial"),
        ("progress", "0002_rls_policies"),
        ("projects", "0003_project_cumulative_progress"),
        ("reports", "0003_report_title_report_updated_at_reportapproval_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "db_table": "documents_documenttype",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("advance", "Advance"),
                            ("report", "Report"),
                            ("product", "Product"),
                            ("call", "Call"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("is_signed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_documents",
                        to="calls.call",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="institutions.institution",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_documents",
                        to="products.researchproduct",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_documents",
                        to="progress.progressreport",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_documents",
                        to="projects.project",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_documents",
                        to="reports.report",
                    ),
                ),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="documents.documenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("object_key", models.CharField(max_length=500)),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
                "db_table": "documents_documentversion",
                "ordering": ["document", "-version"],
            },
        ),
        migrations.CreateModel(
            name="DigitalSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("sha256", models.CharField(max_length=64)),
                ("signer_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "signer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Signature",
                "verbose_name_plural": "Digital Signatures",
                "db_table": "documents_digitalsignature",
                "ordering": ["-signed_at"],
            },
        ),
        migrations.CreateModel(
            name="Minutes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "acta_type",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("comite", "Comité"),
                            ("aprobacion", "Aprobación"),
                            ("cierre", "Cierre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutes",
                        to="documents.document",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutes",
                        to="institutions.institution",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minutes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Minutes",
                "verbose_name_plural": "Minutes",
                "db_table": "documents_minutes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["institution", "is_signed"], name="idx_doc_inst_signed"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["doc_type"], name="idx_doc_type"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["entity_type"], name="idx_doc_entity_type"),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version"), name="unique_version_per_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="digitalsignature",
            constraint=models.UniqueConstraint(
                fields=("document_version",), name="unique_signature_per_version"
            ),
        ),
        migrations.AddIndex(
            model_name="minutes",
            index=models.Index(fields=["institution", "acta_type"], name="idx_minutes_inst_type"),
        ),
        migrations.AddIndex(
            model_name="minutes",
            index=models.Index(fields=["project"], name="idx_minutes_project"),
        ),
        migrations.RunPython(seed_document_types, unseed_document_types),
    ]
