"""
RLS policy tests for institutions app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0003_rls_policies.py:
- Migration class exists in the institutions migrations module
- Contains a RunPython operation
- Depends on 0002_expand_hierarchy
- SQL targets all 5 institution-scoped tables (NOT Institution itself)
- tenant_isolation + superadmin_bypass policies present for each table
- PostgreSQL-only guard (no-op on SQLite)

Spec reference: openspec/changes/institutions/spec.md — Security Requirements
Design reference: openspec/changes/institutions/design.md — RLS Policies
Pattern reference: accounts/0004_rls_policies.py

RED PHASE: Tests fail because 0003_rls_policies.py does not exist.
"""

import importlib
import inspect

from django.db import connection
from django.db.migrations.loader import MigrationLoader

from apps.institutions.models import (
    Facultad,
    ResearchCenter,
    ResearchGroup,
    ResearchLine,
    Sede,
)
from apps.institutions.tests.conftest import (
    FacultadFactory,
    InstitutionFactory,
    ResearchCenterFactory,
    ResearchGroupFactory,
    ResearchLineFactory,
    SedeFactory,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "institutions_sede",
    "institutions_facultad",
    "institutions_researchcenter",
    "institutions_researchgroup",
    "institutions_researchline",
]

# Institution table is explicitly excluded — it has no institution_id column
EXCLUDED_TABLES = [
    "institutions_institution",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the institutions 0003 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("institutions", "0003_rls_policies")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0003 exists and has correct structure."""

    def test_migration_0003_on_disk(self, db):
        """Migration 0003_rls_policies must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0003_rls_policies not found. "
            "Expected at: apps/institutions/migrations/0003_rls_policies.py"
        )

    def test_depends_on_0002(self, db):
        """Migration 0003 must depend on 0002_expand_hierarchy."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("institutions", "0002_expand_hierarchy") in deps, (
            f"Expected dependency on institutions.0002_expand_hierarchy, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0003 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython.RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        """Collect all SQL from the migration module."""
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have RLS policies in the migration SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. "
                f"All institution-scoped tables except Institution must have RLS."
            )

    def test_institution_table_excluded(self, db):
        """Institution table must NOT have RLS policies (no institution_id column)."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        sql = self._get_all_sql()
        for excluded in EXCLUDED_TABLES:
            # Check that tenant_isolation is not applied to the excluded table
            pattern = f"tenant_isolation ON {excluded}"
            assert pattern not in sql, (
                f"'{excluded}' must NOT have RLS policies. "
                f"Institution has no institution_id column."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table must have a tenant_isolation policy filtering by institution_id."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        # Check the module source for a vendor check
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow accounts/0004 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        source = _get_apply_function_source(migration)
        # Check for vendor check or postgres guard pattern
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: Institution excluded from RLS
# ──────────────────────────────────────────────


class TestRLSInstitutionExcluded:
    """Institution table is the root — no institution_id, no RLS."""

    def test_institution_not_in_tenant_tables_list(self, db):
        """Institution must not appear in the list of RLS-enabled tables."""
        migration = _get_migration()
        assert migration is not None, "Migration 0003 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        # The attribute must exist: guarding with hasattr() would let this
        # test pass vacuously if TENANT_SCOPED_TABLES ever disappeared.
        assert hasattr(mod, "TENANT_SCOPED_TABLES"), (
            "Migration 0003 must declare TENANT_SCOPED_TABLES so the excluded "
            "root table can be verified."
        )
        tables = mod.TENANT_SCOPED_TABLES
        assert "institutions_institution" not in tables, (
            "Institution must not be in TENANT_SCOPED_TABLES — it has no institution_id column."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────

TENANT_GUC = "sigpi.institution_id"
BYPASS_GUC = "sigpi.bypass_rls"


def _set_rls(conn, institution_id, bypass):
    """Write the RLS GUCs at connection scope, exactly like production does."""
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [TENANT_GUC, "" if institution_id is None else str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [BYPASS_GUC, "true" if bypass else "false"],
        )


def _seed_institutions(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    _set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="BGA", name="Institution BGA")
    inst_b = InstitutionFactory(code="BGB", name="Institution BGB")
    sede_a = SedeFactory(institution=inst_a)
    sede_b = SedeFactory(institution=inst_b)
    facultad_a = FacultadFactory(institution=inst_a)
    facultad_b = FacultadFactory(institution=inst_b)
    center_a = ResearchCenterFactory(institution=inst_a)
    center_b = ResearchCenterFactory(institution=inst_b)
    group_a = ResearchGroupFactory(institution=inst_a, center=center_a)
    group_b = ResearchGroupFactory(institution=inst_b, center=center_b)
    line_a = ResearchLineFactory(institution=inst_a, group=group_a)
    line_b = ResearchLineFactory(institution=inst_b, group=group_b)
    _set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "sede_a": sede_a,
        "sede_b": sede_b,
        "facultad_a": facultad_a,
        "facultad_b": facultad_b,
        "center_a": center_a,
        "center_b": center_b,
        "group_a": group_a,
        "group_b": group_b,
        "line_a": line_a,
        "line_b": line_b,
    }


def _assert_only_a_visible(model, pk_a, pk_b):
    """Non-vacuous assertion pair: A's row visible, B's row denied."""
    assert model.objects.filter(pk=pk_a).exists(), (
        f"{model.__name__}: institution A's seeded row is not visible under "
        f"institution A's tenant context."
    )
    assert model.objects.filter(pk=pk_b).count() == 0, (
        f"{model.__name__}: institution B's seeded row leaked into institution A's tenant context."
    )


def _assert_both_visible(model, pk_a, pk_b):
    """Bypass must reveal both institutions' rows, not merely zero rows."""
    both = model.objects.filter(pk__in=[pk_a, pk_b]).count()
    assert both == 2, (
        f"{model.__name__}: superadmin bypass exposed {both} of 2 seeded rows; "
        f"it must reveal more than a single tenant scope."
    )


class TestRLSEnforcement:
    """Cross-institution isolation for every protected institutions table."""

    def test_cross_institution_sede_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_institutions(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(Sede, rows["sede_a"].pk, rows["sede_b"].pk)

    def test_cross_institution_facultad_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_institutions(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(Facultad, rows["facultad_a"].pk, rows["facultad_b"].pk)

    def test_cross_institution_researchcenter_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_institutions(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ResearchCenter, rows["center_a"].pk, rows["center_b"].pk)

    def test_cross_institution_researchgroup_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_institutions(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ResearchGroup, rows["group_a"].pk, rows["group_b"].pk)

    def test_cross_institution_researchline_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_institutions(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ResearchLine, rows["line_a"].pk, rows["line_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_institutions(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=True)
        _assert_both_visible(Sede, rows["sede_a"].pk, rows["sede_b"].pk)
        _assert_both_visible(Facultad, rows["facultad_a"].pk, rows["facultad_b"].pk)
        _assert_both_visible(ResearchCenter, rows["center_a"].pk, rows["center_b"].pk)
        _assert_both_visible(ResearchGroup, rows["group_a"].pk, rows["group_b"].pk)
        _assert_both_visible(ResearchLine, rows["line_a"].pk, rows["line_b"].pk)
