"""
RLS policy tests for the reports app — STRICT TDD.

Tests verify the existence and structure of migration 0004_reporttemplate_rls.py,
which closes the isolation gap left by ``reports_reporttemplate`` being created
after ``reports/0002`` applied the app's policies:

- Migration class exists in the reports migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0003_report_title_report_updated_at_reportapproval_status_and_more
- SQL targets reports_reporttemplate
- tenant_isolation + superadmin_bypass policies present
- Uses the hardened GUC casts required by the repo-wide policy contract
- PostgreSQL-only guard (no-op on SQLite)

Pattern reference: apps/budgets/tests/test_rls.py

Spec reference:  odd/tasks/rls-enforcement-completion.md — acceptance criterion 5
"""

import importlib
import inspect

from django.db import connection
from django.db.migrations.loader import MigrationLoader

from apps.institutions.tests.conftest import InstitutionFactory
from apps.reports.models import Report, ReportApproval, ReportTemplate
from apps.reports.tests.conftest import (
    ReportApprovalFactory,
    ReportFactory,
    ReportTemplateFactory,
)

TABLE = "reports_reporttemplate"

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the reports 0004 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("reports", "0004_reporttemplate_rls")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_module():
    """Import the 0004 migration module."""
    migration = _get_migration()
    if migration is None:
        return None
    return importlib.import_module(migration.__class__.__module__)


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


def _get_migration_0002():
    """Load the reports 0002 migration (Report + ReportApproval policies)."""
    loader = MigrationLoader(connection)
    key = ("reports", "0002_rls_policies")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _sql_from_module(mod):
    """Collect every policy SQL string declared by a migration module."""
    if mod is None:
        return ""
    return "\n".join(
        val
        for attr_name in dir(mod)
        if isinstance((val := getattr(mod, attr_name)), str) and "tenant_isolation" in val
    )


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0004 exists and has correct structure."""

    def test_migration_0004_on_disk(self, db):
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0004_reporttemplate_rls not found. "
            "Expected at: apps/reports/migrations/0004_reporttemplate_rls.py"
        )

    def test_depends_on_0003(self, db):
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        expected = ("reports", "0003_report_title_report_updated_at_reportapproval_status_and_more")
        assert expected in deps, f"Expected dependency on {expected}, got: {deps}"

    def test_has_run_python_operation(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0004 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets the template table."""

    def _get_all_sql(self):
        return _sql_from_module(_get_module())

    def test_table_in_sql(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert TABLE in sql, f"Table '{TABLE}' missing from RLS migration SQL."

    def test_tenant_isolation_policy(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert f"CREATE POLICY tenant_isolation ON {TABLE}" in sql, (
            f"tenant_isolation policy missing for '{TABLE}'"
        )

    def test_superadmin_bypass_policy(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert f"CREATE POLICY superadmin_bypass ON {TABLE}" in sql, (
            f"superadmin_bypass policy missing for '{TABLE}'"
        )

    def test_enable_rls(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY" in sql, (
            f"ENABLE ROW LEVEL SECURITY missing for '{TABLE}'"
        )

    def test_uses_hardened_tenant_cast(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), f"{TABLE} must use the hardened institution_id cast."

    def test_uses_hardened_bypass_cast(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert "NULLIF(current_setting('sigpi.bypass_rls', true), '')::bool = true" in sql, (
            f"{TABLE} must use the hardened bypass cast."
        )

    def test_every_policy_is_droppable(self, db):
        mod = _get_module()
        assert mod is not None, "Migration 0004 missing"
        disable = getattr(mod, "DISABLE_RLS_SQL", "")
        for policy in EXPECTED_POLICIES:
            assert f"DROP POLICY IF EXISTS {policy} ON {TABLE}" in disable, (
                f"DROP POLICY IF EXISTS {policy} missing from reverse SQL."
            )
        assert f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY" in disable, (
            f"DISABLE ROW LEVEL SECURITY missing from reverse SQL for '{TABLE}'"
        )


# ──────────────────────────────────────────────
# Test: 0002 tables (reports_report + reports_reportapproval)
# ──────────────────────────────────────────────

PARENT_TABLE_0002 = "reports_report"
CHILD_TABLES_0002 = [
    "reports_reportapproval",
]


class TestRLSReportTables0002:
    """Structural coverage for the reports 0002 policy pair."""

    def _get_all_sql(self):
        migration = _get_migration_0002()
        if migration is None:
            return ""
        mod = importlib.import_module(migration.__class__.__module__)
        return _sql_from_module(mod)

    def test_migration_0002_on_disk(self, db):
        migration = _get_migration_0002()
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/reports/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        migration = _get_migration_0002()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("reports", "0001_initial") in deps, (
            f"Expected dependency on reports.0001_initial, got: {deps}"
        )

    def test_has_reverse_code(self, db):
        migration = _get_migration_0002()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert run_python_ops, "Migration 0002 must contain a RunPython operation"
        for op in run_python_ops:
            assert op.reverse_code is not None, "RunPython RLS must have reverse_code for rollback"

    def test_both_tables_covered(self, db):
        assert _get_migration_0002() is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in [PARENT_TABLE_0002, *CHILD_TABLES_0002]:
            assert table in sql, f"Table '{table}' missing from RLS migration SQL."

    def test_policies_per_table(self, db):
        assert _get_migration_0002() is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in [PARENT_TABLE_0002, *CHILD_TABLES_0002]:
            assert f"CREATE POLICY tenant_isolation ON {table}" in sql, (
                f"tenant_isolation policy missing for '{table}'"
            )
            assert f"CREATE POLICY superadmin_bypass ON {table}" in sql, (
                f"superadmin_bypass policy missing for '{table}'"
            )
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_uses_direct_institution_id(self, db):
        assert _get_migration_0002() is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), f"{PARENT_TABLE_0002} must use the hardened direct institution_id cast."

    def test_child_uses_subquery(self, db):
        assert _get_migration_0002() is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert "SELECT id FROM reports_report" in sql, (
            f"{CHILD_TABLES_0002[0]} must subquery reports_report by institution_id."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        mod = _get_module()
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow reports/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0004 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────

TENANT_GUC = "sigpi.institution_id"
BYPASS_GUC = "sigpi.bypass_rls"


def _set_rls(conn, institution_id, bypass):
    """Write the RLS GUCs at connection scope, exactly like production does."""
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [TENANT_GUC, "" if institution_id is None else str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [BYPASS_GUC, "true" if bypass else "false"],
        )


def _seed_reports(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    _set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="BGA", name="Institution BGA")
    inst_b = InstitutionFactory(code="BGB", name="Institution BGB")
    report_a = ReportFactory(institution=inst_a)
    report_b = ReportFactory(institution=inst_b)
    approval_a = ReportApprovalFactory(report=report_a)
    approval_b = ReportApprovalFactory(report=report_b)
    template_a = ReportTemplateFactory(institution=inst_a)
    template_b = ReportTemplateFactory(institution=inst_b)
    _set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "report_a": report_a,
        "report_b": report_b,
        "approval_a": approval_a,
        "approval_b": approval_b,
        "template_a": template_a,
        "template_b": template_b,
    }


def _assert_only_a_visible(model, pk_a, pk_b):
    """Non-vacuous assertion pair: A's row visible, B's row denied."""
    assert model.objects.filter(pk=pk_a).exists(), (
        f"{model.__name__}: institution A's seeded row is not visible under "
        f"institution A's tenant context."
    )
    assert model.objects.filter(pk=pk_b).count() == 0, (
        f"{model.__name__}: institution B's seeded row leaked into institution A's tenant context."
    )


def _assert_both_visible(model, pk_a, pk_b):
    """Bypass must reveal both institutions' rows, not merely zero rows."""
    both = model.objects.filter(pk__in=[pk_a, pk_b]).count()
    assert both == 2, (
        f"{model.__name__}: superadmin bypass exposed {both} of 2 seeded rows; "
        f"it must reveal more than a single tenant scope."
    )


class TestRLSEnforcement:
    """Cross-institution isolation for every protected reports table."""

    def test_cross_institution_report_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(Report, rows["report_a"].pk, rows["report_b"].pk)

    def test_cross_institution_approval_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ReportApproval, rows["approval_a"].pk, rows["approval_b"].pk)

    def test_cross_institution_template_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ReportTemplate, rows["template_a"].pk, rows["template_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=True)
        _assert_both_visible(Report, rows["report_a"].pk, rows["report_b"].pk)
        _assert_both_visible(ReportApproval, rows["approval_a"].pk, rows["approval_b"].pk)
        _assert_both_visible(ReportTemplate, rows["template_a"].pk, rows["template_b"].pk)
