"""
RLS policy tests for the reports app — STRICT TDD.

Tests verify the existence and structure of migration 0004_reporttemplate_rls.py,
which closes the isolation gap left by ``reports_reporttemplate`` being created
after ``reports/0002`` applied the app's policies:

- Migration class exists in the reports migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0003_report_title_report_updated_at_reportapproval_status_and_more
- SQL targets reports_reporttemplate
- tenant_isolation + superadmin_bypass policies present
- Uses the hardened GUC casts required by the repo-wide policy contract
- PostgreSQL-only guard (no-op on SQLite)

Pattern reference: apps/budgets/tests/test_rls.py

Spec reference:  odd/tasks/rls-enforcement-completion.md — acceptance criterion 5
"""

import importlib
import inspect

from apps.institutions.tests.conftest import InstitutionFactory
from apps.reports.models import Report, ReportApproval, ReportTemplate
from apps.reports.tests.conftest import (
    ReportApprovalFactory,
    ReportFactory,
    ReportTemplateFactory,
)
from tests.rls_helpers import (
    assert_both_visible,
    assert_only_a_visible,
    get_all_sql,
    get_apply_function_source,
    load_migration,
    policy_using,
    set_rls,
)

TABLE = "reports_reporttemplate"

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0004 exists and has correct structure."""

    def test_migration_0004_on_disk(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, (
            "Migration 0004_reporttemplate_rls not found. "
            "Expected at: apps/reports/migrations/0004_reporttemplate_rls.py"
        )

    def test_depends_on_0003(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        expected = ("reports", "0003_report_title_report_updated_at_reportapproval_status_and_more")
        assert expected in deps, f"Expected dependency on {expected}, got: {deps}"

    def test_has_run_python_operation(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0004 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets the template table."""

    def test_table_in_sql(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        sql = get_all_sql(migration)
        assert policy_using(sql, TABLE) is not None, (
            f"Table '{TABLE}' has no CREATE POLICY tenant_isolation with a USING clause."
        )

    def test_tenant_isolation_policy(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        sql = get_all_sql(migration)
        predicate = policy_using(sql, TABLE)
        assert predicate is not None, (
            f"'{TABLE}': no CREATE POLICY tenant_isolation with a USING clause"
        )
        assert "sigpi.institution_id" in predicate, (
            f"'{TABLE}': tenant_isolation predicate does not scope by the tenant GUC: {predicate!r}"
        )

    def test_superadmin_bypass_policy(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        sql = get_all_sql(migration)
        assert f"CREATE POLICY superadmin_bypass ON {TABLE}" in sql, (
            f"superadmin_bypass policy missing for '{TABLE}'"
        )

    def test_enable_rls(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        sql = get_all_sql(migration)
        assert f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY" in sql, (
            f"ENABLE ROW LEVEL SECURITY missing for '{TABLE}'"
        )

    def test_uses_hardened_tenant_cast(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        sql = get_all_sql(migration)
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), f"{TABLE} must use the hardened institution_id cast."

    def test_uses_hardened_bypass_cast(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        sql = get_all_sql(migration)
        assert "NULLIF(current_setting('sigpi.bypass_rls', true), '')::bool = true" in sql, (
            f"{TABLE} must use the hardened bypass cast."
        )

    def test_every_policy_is_droppable(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        mod = importlib.import_module(migration.__class__.__module__)
        disable = getattr(mod, "DISABLE_RLS_SQL", "")
        for policy in EXPECTED_POLICIES:
            assert f"DROP POLICY IF EXISTS {policy} ON {TABLE}" in disable, (
                f"DROP POLICY IF EXISTS {policy} missing from reverse SQL."
            )
        assert f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY" in disable, (
            f"DISABLE ROW LEVEL SECURITY missing from reverse SQL for '{TABLE}'"
        )


# ──────────────────────────────────────────────
# Test: 0002 tables (reports_report + reports_reportapproval)
# ──────────────────────────────────────────────

PARENT_TABLE_0002 = "reports_report"
CHILD_TABLES_0002 = [
    "reports_reportapproval",
]


class TestRLSReportTables0002:
    """Structural coverage for the reports 0002 policy pair."""

    def test_migration_0002_on_disk(self, db):
        migration = load_migration("reports", "0002_rls_policies")
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/reports/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        migration = load_migration("reports", "0002_rls_policies")
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("reports", "0001_initial") in deps, (
            f"Expected dependency on reports.0001_initial, got: {deps}"
        )

    def test_has_reverse_code(self, db):
        migration = load_migration("reports", "0002_rls_policies")
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert run_python_ops, "Migration 0002 must contain a RunPython operation"
        for op in run_python_ops:
            assert op.reverse_code is not None, "RunPython RLS must have reverse_code for rollback"

    def test_both_tables_covered(self, db):
        migration = load_migration("reports", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in [PARENT_TABLE_0002, *CHILD_TABLES_0002]:
            assert policy_using(sql, table) is not None, (
                f"Table '{table}' has no CREATE POLICY tenant_isolation with a USING clause."
            )

    def test_policies_per_table(self, db):
        migration = load_migration("reports", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        for table in [PARENT_TABLE_0002, *CHILD_TABLES_0002]:
            predicate = policy_using(sql, table)
            assert predicate is not None, (
                f"'{table}': no CREATE POLICY tenant_isolation with a USING clause"
            )
            assert "sigpi.institution_id" in predicate, (
                f"'{table}': tenant_isolation predicate does not scope by the tenant GUC: "
                f"{predicate!r}"
            )
            assert f"CREATE POLICY superadmin_bypass ON {table}" in sql, (
                f"superadmin_bypass policy missing for '{table}'"
            )
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_uses_direct_institution_id(self, db):
        migration = load_migration("reports", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        predicate = policy_using(sql, PARENT_TABLE_0002)
        assert predicate is not None, f"{PARENT_TABLE_0002}: no tenant_isolation USING clause"
        assert "institution_id" in predicate, (
            f"{PARENT_TABLE_0002} must use the hardened direct institution_id cast."
        )

    def test_child_uses_subquery(self, db):
        migration = load_migration("reports", "0002_rls_policies")
        assert migration is not None, "Migration 0002 missing"
        sql = get_all_sql(migration)
        predicate = policy_using(sql, CHILD_TABLES_0002[0])
        assert predicate is not None, f"{CHILD_TABLES_0002[0]}: no tenant_isolation USING clause"
        assert "report_id" in predicate and "reports_report" in predicate, (
            f"{CHILD_TABLES_0002[0]} must subquery reports_report by institution_id: {predicate!r}"
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        mod = importlib.import_module(migration.__class__.__module__)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow reports/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        migration = load_migration("reports", "0004_reporttemplate_rls")
        assert migration is not None, "Migration 0004 missing"
        source = get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────


def _seed_reports(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="BGA", name="Institution BGA")
    inst_b = InstitutionFactory(code="BGB", name="Institution BGB")
    report_a = ReportFactory(institution=inst_a)
    report_b = ReportFactory(institution=inst_b)
    approval_a = ReportApprovalFactory(report=report_a)
    approval_b = ReportApprovalFactory(report=report_b)
    template_a = ReportTemplateFactory(institution=inst_a)
    template_b = ReportTemplateFactory(institution=inst_b)
    set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "report_a": report_a,
        "report_b": report_b,
        "approval_a": approval_a,
        "approval_b": approval_b,
        "template_a": template_a,
        "template_b": template_b,
    }


class TestRLSEnforcement:
    """Cross-institution isolation for every protected reports table."""

    def test_cross_institution_report_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(Report, rows["report_a"].pk, rows["report_b"].pk)

    def test_cross_institution_approval_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(ReportApproval, rows["approval_a"].pk, rows["approval_b"].pk)

    def test_cross_institution_template_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=False)
        assert_only_a_visible(ReportTemplate, rows["template_a"].pk, rows["template_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_reports(conn)

        set_rls(conn, rows["inst_a"].pk, bypass=True)
        assert_both_visible(Report, rows["report_a"].pk, rows["report_b"].pk)
        assert_both_visible(ReportApproval, rows["approval_a"].pk, rows["approval_b"].pk)
        assert_both_visible(ReportTemplate, rows["template_a"].pk, rows["template_b"].pk)
