"""
RLS policy tests for the reports app — STRICT TDD.

Tests verify the existence and structure of migration 0004_reporttemplate_rls.py,
which closes the isolation gap left by ``reports_reporttemplate`` being created
after ``reports/0002`` applied the app's policies:

- Migration class exists in the reports migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0003_report_title_report_updated_at_reportapproval_status_and_more
- SQL targets reports_reporttemplate
- tenant_isolation + superadmin_bypass policies present
- Uses the hardened GUC casts required by the repo-wide policy contract
- PostgreSQL-only guard (no-op on SQLite)

Pattern reference: apps/budgets/tests/test_rls.py

Spec reference:  odd/tasks/rls-enforcement-completion.md — acceptance criterion 5
"""

import importlib
import inspect

from django.db import connection
from django.db.migrations.loader import MigrationLoader

TABLE = "reports_reporttemplate"

EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the reports 0004 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("reports", "0004_reporttemplate_rls")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_module():
    """Import the 0004 migration module."""
    migration = _get_migration()
    if migration is None:
        return None
    return importlib.import_module(migration.__class__.__module__)


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0004 exists and has correct structure."""

    def test_migration_0004_on_disk(self, db):
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0004_reporttemplate_rls not found. "
            "Expected at: apps/reports/migrations/0004_reporttemplate_rls.py"
        )

    def test_depends_on_0003(self, db):
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        expected = ("reports", "0003_report_title_report_updated_at_reportapproval_status_and_more")
        assert expected in deps, f"Expected dependency on {expected}, got: {deps}"

    def test_has_run_python_operation(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0004 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets the template table."""

    def _get_all_sql(self):
        mod = _get_module()
        if mod is None:
            return ""
        return "\n".join(
            val
            for attr_name in dir(mod)
            if isinstance((val := getattr(mod, attr_name)), str) and "tenant_isolation" in val
        )

    def test_table_in_sql(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert TABLE in sql, f"Table '{TABLE}' missing from RLS migration SQL."

    def test_tenant_isolation_policy(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert f"CREATE POLICY tenant_isolation ON {TABLE}" in sql, (
            f"tenant_isolation policy missing for '{TABLE}'"
        )

    def test_superadmin_bypass_policy(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert f"CREATE POLICY superadmin_bypass ON {TABLE}" in sql, (
            f"superadmin_bypass policy missing for '{TABLE}'"
        )

    def test_enable_rls(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY" in sql, (
            f"ENABLE ROW LEVEL SECURITY missing for '{TABLE}'"
        )

    def test_uses_hardened_tenant_cast(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), f"{TABLE} must use the hardened institution_id cast."

    def test_uses_hardened_bypass_cast(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        sql = self._get_all_sql()
        assert "NULLIF(current_setting('sigpi.bypass_rls', true), '')::bool = true" in sql, (
            f"{TABLE} must use the hardened bypass cast."
        )

    def test_every_policy_is_droppable(self, db):
        mod = _get_module()
        assert mod is not None, "Migration 0004 missing"
        disable = getattr(mod, "DISABLE_RLS_SQL", "")
        for policy in EXPECTED_POLICIES:
            assert f"DROP POLICY IF EXISTS {policy} ON {TABLE}" in disable, (
                f"DROP POLICY IF EXISTS {policy} missing from reverse SQL."
            )
        assert f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY" in disable, (
            f"DISABLE ROW LEVEL SECURITY missing from reverse SQL for '{TABLE}'"
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        assert _get_migration() is not None, "Migration 0004 missing"
        mod = _get_module()
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow reports/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        migration = _get_migration()
        assert migration is not None, "Migration 0004 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )
