# Generated by Django 5.1.15 on 2026-07-22 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "0004_alter_facultad_status_alter_institution_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("project", "Project Report"),
                            ("researcher", "Researcher Report"),
                            ("center", "Center Report"),
                            ("advances", "Advances Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("report_version", models.PositiveIntegerField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Approval",
                "verbose_name_plural": "Report Approvals",
                "db_table": "reports_reportapproval",
                "ordering": ["report", "-approved_at"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["institution", "report_type", "status"], name="idx_reports_inst_type_status"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["entity_id", "report_type"], name="idx_reports_entity_type"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["created_by"], name="idx_reports_created_by"),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="check_report_version_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="reportapproval",
            index=models.Index(fields=["report", "-approved_at"], name="idx_approval_report_time"),
        ),
        migrations.AddIndex(
            model_name="reportapproval",
            index=models.Index(fields=["approved_by"], name="idx_approval_approved_by"),
        ),
        migrations.AddConstraint(
            model_name="reportapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("report_version__gte", 1)),
                name="check_approval_version_positive",
            ),
        ),
    ]
