"""
RLS policy tests for projects app — STRICT TDD (RED phase).

Tests verify the existence and structure of migration 0002_rls_policies.py:
- Migration class exists in the projects migrations module
- Contains a RunPython operation with reverse_code
- Depends on 0001_initial
- SQL targets all 5 project tables
- tenant_isolation + superadmin_bypass policies present for each table
- Parent table (projects_project) uses direct institution_id
- Child tables use subquery via project_id
- PostgreSQL-only guard (no-op on SQLite)

Spec reference:  openspec/changes/projects/spec.md — Security Requirements
Design reference: openspec/changes/projects/design.md — RLS Policies
Pattern reference: researchers/migrations/0002_rls_policies.py

RED PHASE: Tests fail because 0002_rls_policies.py does not exist.
"""

import importlib
import inspect

from django.db import connection
from django.db.migrations.loader import MigrationLoader

from apps.institutions.tests.conftest import InstitutionFactory
from apps.projects.models import (
    Project,
    ProjectDocument,
    ProjectMember,
    ProjectObservation,
    ProjectStateLog,
)
from apps.projects.tests.conftest import (
    ProjectDocumentFactory,
    ProjectFactory,
    ProjectMemberFactory,
    ProjectObservationFactory,
    ProjectStateLogFactory,
)

# ──────────────────────────────────────────────
# Tables that MUST have RLS policies
# ──────────────────────────────────────────────

EXPECTED_RLS_TABLES = [
    "projects_project",
    "projects_projectmember",
    "projects_projectdocument",
    "projects_projectobservation",
    "projects_projectstatelog",
]

# Child tables that use a subquery (no direct institution_id)
CHILD_TABLES = [
    "projects_projectmember",
    "projects_projectdocument",
    "projects_projectobservation",
    "projects_projectstatelog",
]

# Policies that must exist per table
EXPECTED_POLICIES = [
    "tenant_isolation",
    "superadmin_bypass",
]


# ──────────────────────────────────────────────
# Migration loader helper
# ──────────────────────────────────────────────


def _get_migration():
    """Load the projects 0002 migration from the migration loader."""
    loader = MigrationLoader(connection)
    key = ("projects", "0002_rls_policies")
    if key not in loader.disk_migrations:
        return None
    return loader.disk_migrations[key]


def _get_apply_function_source(migration):
    """Extract the source code of the RunPython forward function."""
    for operation in migration.operations:
        if hasattr(operation, "code") and operation.code is not None:
            return inspect.getsource(operation.code)
    return ""


# ──────────────────────────────────────────────
# Test: Migration Existence and Structure
# ──────────────────────────────────────────────


class TestRLSMigrationExists:
    """Verify migration 0002 exists and has correct structure."""

    def test_migration_0002_on_disk(self, db):
        """Migration 0002_rls_policies must exist on disk."""
        migration = _get_migration()
        assert migration is not None, (
            "Migration 0002_rls_policies not found. "
            "Expected at: apps/projects/migrations/0002_rls_policies.py"
        )

    def test_depends_on_0001(self, db):
        """Migration 0002 must depend on 0001_initial."""
        migration = _get_migration()
        assert migration is not None
        deps = [(app, name) for (app, name) in migration.dependencies]
        assert ("projects", "0001_initial") in deps, (
            f"Expected dependency on projects.0001_initial, got: {deps}"
        )

    def test_has_run_python_operation(self, db):
        """Migration must contain a RunPython operation."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        run_python_ops = [op for op in migration.operations if isinstance(op, RunPython)]
        assert len(run_python_ops) > 0, (
            "Migration 0002 must contain at least one RunPython operation"
        )

    def test_has_reverse_code(self, db):
        """RunPython must have a reverse_code for rollback."""
        migration = _get_migration()
        assert migration is not None
        from django.db.migrations import RunPython

        for op in migration.operations:
            if isinstance(op, RunPython):
                assert op.reverse_code is not None, (
                    "RunPython.RLS must have reverse_code for rollback"
                )


# ──────────────────────────────────────────────
# Test: RLS Policy SQL Content
# ──────────────────────────────────────────────


class TestRLSPolicySQL:
    """Verify the SQL generated by the RLS migration targets expected tables."""

    def _get_all_sql(self):
        """Collect all SQL from the migration module."""
        migration = _get_migration()
        if migration is None:
            return ""
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        sql_parts = []
        for attr_name in dir(mod):
            val = getattr(mod, attr_name)
            if isinstance(val, str) and "tenant_isolation" in val:
                sql_parts.append(val)
        return "\n".join(sql_parts)

    def test_all_expected_tables_in_sql(self, db):
        """Every expected table must have RLS policies in the migration SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert table in sql, (
                f"Table '{table}' missing from RLS migration SQL. "
                f"All 5 project tables must have RLS."
            )

    def test_tenant_isolation_policy_per_table(self, db):
        """Each table must have a tenant_isolation policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY tenant_isolation ON {table}"
            assert pattern in sql, f"tenant_isolation policy missing for '{table}'"

    def test_superadmin_bypass_policy_per_table(self, db):
        """Each table must have a superadmin_bypass policy."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            pattern = f"CREATE POLICY superadmin_bypass ON {table}"
            assert pattern in sql, f"superadmin_bypass policy missing for '{table}'"

    def test_each_table_has_enable_rls(self, db):
        """Each table must have ENABLE ROW LEVEL SECURITY."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in EXPECTED_RLS_TABLES:
            assert f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY" in sql, (
                f"ENABLE ROW LEVEL SECURITY missing for '{table}'"
            )

    def test_parent_table_uses_direct_institution_id(self, db):
        """Project table must filter by institution_id directly (has the column)."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        assert (
            "institution_id = NULLIF(current_setting('sigpi.institution_id', true), '')::uuid"
            in sql
        ), "projects_project must use direct institution_id filter. Child tables use subquery."

    def test_child_tables_use_subquery(self, db):
        """Child tables must filter via subquery through project_id."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        sql = self._get_all_sql()
        for table in CHILD_TABLES:
            assert "project_id IN" in sql and "projects_project" in sql, (
                f"Child table '{table}' must use a subquery through "
                f"project_id → projects_project.institution_id."
            )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only Guard
# ──────────────────────────────────────────────


class TestRLSPostgresGuard:
    """Verify the migration guards against non-PostgreSQL backends."""

    def test_has_is_postgresql_check(self, db):
        """Migration must contain a PostgreSQL vendor check."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        module_name = migration.__class__.__module__
        mod = importlib.import_module(module_name)
        source = inspect.getsource(mod)
        assert "vendor" in source.lower() or "postgresql" in source.lower(), (
            "Migration must guard against non-PostgreSQL backends "
            "(e.g., SQLite in tests). Follow researchers/0002 pattern."
        )

    def test_forward_function_has_postgres_guard(self, db):
        """The apply function must check for PostgreSQL before executing SQL."""
        migration = _get_migration()
        assert migration is not None, "Migration 0002 missing"
        source = _get_apply_function_source(migration)
        has_guard = (
            "vendor" in source.lower()
            or "postgresql" in source.lower()
            or "_is_postgresql" in source
        )
        assert has_guard, (
            "Forward function must guard against non-PostgreSQL. "
            "Add _is_postgresql() check before schema_editor.execute()."
        )


# ──────────────────────────────────────────────
# Test: PostgreSQL-only enforcement (skip on SQLite via postgres_app_role)
# ──────────────────────────────────────────────

TENANT_GUC = "sigpi.institution_id"
BYPASS_GUC = "sigpi.bypass_rls"


def _set_rls(conn, institution_id, bypass):
    """Write the RLS GUCs at connection scope, exactly like production does."""
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [TENANT_GUC, "" if institution_id is None else str(institution_id)],
        )
        cursor.execute(
            "SELECT set_config(%s, %s, false)",
            [BYPASS_GUC, "true" if bypass else "false"],
        )


def _seed_projects(conn):
    """Seed one institution-A and one institution-B row per protected table.

    Every protected row is inserted under a bypass context, because
    ``sigpi_app`` cannot see or write a foreign institution's rows otherwise.
    Seeding restores the restrictive default, so each test must opt in to a
    tenant context before it reads anything.
    """
    _set_rls(conn, None, bypass=True)
    inst_a = InstitutionFactory(code="PRA", name="Institution PRA")
    inst_b = InstitutionFactory(code="PRB", name="Institution PRB")
    project_a = ProjectFactory(institution=inst_a)
    project_b = ProjectFactory(institution=inst_b)
    member_a = ProjectMemberFactory(project=project_a)
    member_b = ProjectMemberFactory(project=project_b)
    document_a = ProjectDocumentFactory(project=project_a)
    document_b = ProjectDocumentFactory(project=project_b)
    observation_a = ProjectObservationFactory(project=project_a)
    observation_b = ProjectObservationFactory(project=project_b)
    log_a = ProjectStateLogFactory(project=project_a)
    log_b = ProjectStateLogFactory(project=project_b)
    _set_rls(conn, None, bypass=False)
    return {
        "inst_a": inst_a,
        "project_a": project_a,
        "project_b": project_b,
        "member_a": member_a,
        "member_b": member_b,
        "document_a": document_a,
        "document_b": document_b,
        "observation_a": observation_a,
        "observation_b": observation_b,
        "log_a": log_a,
        "log_b": log_b,
    }


def _assert_only_a_visible(model, pk_a, pk_b):
    """Non-vacuous assertion pair: A's row visible, B's row denied."""
    assert model.objects.filter(pk=pk_a).exists(), (
        f"{model.__name__}: institution A's seeded row is not visible under "
        f"institution A's tenant context."
    )
    assert model.objects.filter(pk=pk_b).count() == 0, (
        f"{model.__name__}: institution B's seeded row leaked into institution A's tenant context."
    )


def _assert_both_visible(model, pk_a, pk_b):
    """Bypass must reveal both institutions' rows, not merely zero rows."""
    both = model.objects.filter(pk__in=[pk_a, pk_b]).count()
    assert both == 2, (
        f"{model.__name__}: superadmin bypass exposed {both} of 2 seeded rows; "
        f"it must reveal more than a single tenant scope."
    )


class TestRLSEnforcement:
    """Cross-institution isolation for every protected projects table."""

    def test_cross_institution_project_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_projects(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(Project, rows["project_a"].pk, rows["project_b"].pk)

    def test_cross_institution_member_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_projects(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ProjectMember, rows["member_a"].pk, rows["member_b"].pk)

    def test_cross_institution_document_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_projects(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ProjectDocument, rows["document_a"].pk, rows["document_b"].pk)

    def test_cross_institution_observation_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_projects(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(
            ProjectObservation, rows["observation_a"].pk, rows["observation_b"].pk
        )

    def test_cross_institution_state_log_invisible(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_projects(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=False)
        _assert_only_a_visible(ProjectStateLog, rows["log_a"].pk, rows["log_b"].pk)

    def test_superadmin_bypass_sees_all(self, postgres_app_role):
        conn = postgres_app_role
        rows = _seed_projects(conn)

        _set_rls(conn, rows["inst_a"].pk, bypass=True)
        _assert_both_visible(Project, rows["project_a"].pk, rows["project_b"].pk)
        _assert_both_visible(ProjectMember, rows["member_a"].pk, rows["member_b"].pk)
        _assert_both_visible(ProjectDocument, rows["document_a"].pk, rows["document_b"].pk)
        _assert_both_visible(ProjectObservation, rows["observation_a"].pk, rows["observation_b"].pk)
        _assert_both_visible(ProjectStateLog, rows["log_a"].pk, rows["log_b"].pk)
