# Generated by Django 5.1.15 on 2026-07-23 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0004_alter_facultad_status_alter_institution_status_and_more'),
        ('projects', '0002_rls_policies'),
        ('researchers', '0002_rls_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('articulo', 'Artículo'), ('libro', 'Libro'), ('capitulo', 'Capítulo'), ('software', 'Software'), ('prototipo', 'Prototipo'), ('evento', 'Evento'), ('consultoria', 'Consultoría'), ('diseno_industrial', 'Diseño Industrial'), ('innovacion_proceso', 'Innovación de Proceso'), ('innovacion_gestion', 'Innovación de Gestión'), ('carta', 'Carta')], max_length=30)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='institutions.institution')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Product',
                'verbose_name_plural': 'Research Products',
                'db_table': 'products_researchproduct',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_principal', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_authorships', to='researchers.researcher')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='products.researchproduct')),
            ],
            options={
                'verbose_name': 'Product Author',
                'verbose_name_plural': 'Product Authors',
                'db_table': 'products_productauthor',
                'ordering': ['product', 'order', 'researcher'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=50)),
                ('external_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='products.researchproduct')),
            ],
            options={
                'verbose_name': 'Product Attachment',
                'verbose_name_plural': 'Product Attachments',
                'db_table': 'products_productattachment',
                'ordering': ['product', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchproduct',
            index=models.Index(fields=['institution', 'type'], name='idx_product_inst_type'),
        ),
        migrations.AddIndex(
            model_name='researchproduct',
            index=models.Index(fields=['institution', 'publication_year'], name='idx_product_inst_year'),
        ),
        migrations.AddIndex(
            model_name='researchproduct',
            index=models.Index(fields=['project'], name='idx_product_project'),
        ),
        migrations.AddConstraint(
            model_name='productauthor',
            constraint=models.UniqueConstraint(fields=('product', 'researcher'), name='unique_product_researcher'),
        ),
    ]
